export type Topic = 'Überblick & Vergleich' | 'Buddhismus' | 'Buddhas Leben & Lehre' | 'Hinduismus' | 'Hinduistische Gottheiten';
export type Question = { id: string; topic: Topic; prompt: string; options: string[]; answer: number; explanation: string };
export type ItemStat = { attempts: number; correct: number };

export const topics: Topic[] = ['Überblick & Vergleich', 'Buddhismus', 'Buddhas Leben & Lehre', 'Hinduismus', 'Hinduistische Gottheiten'];

type Fact = { label: string; prompt: string; correct: string; wrong: [string, string]; explanation: string };

function questionsFromFacts(topic: Topic, prefix: string, facts: Fact[]): Question[] {
  return facts.flatMap((fact, index) => {
    const options = [fact.correct, ...fact.wrong];
    return [
      { id: `${prefix}${index + 1}a`, topic, prompt: fact.prompt, options, answer: 0, explanation: fact.explanation },
      { id: `${prefix}${index + 1}b`, topic, prompt: `Welche Aussage erklärt „${fact.label}“ richtig?`, options, answer: 0, explanation: fact.explanation },
    ];
  });
}

const overviewFacts: Fact[] = [
  { label: 'fünf Weltreligionen', prompt: 'Welche fünf Weltreligionen gehören zu diesem Lernstoff?', correct: 'Christentum, Islam, Judentum, Hinduismus und Buddhismus', wrong: ['Christentum, Islam, Sikhismus, Taoismus und Jainismus', 'Judentum, Hinduismus, Schintoismus, Bahai und Taoismus'], explanation: 'Im Heft werden Christentum, Islam, Judentum, Hinduismus und Buddhismus miteinander verglichen.' },
  { label: 'Teil 2', prompt: 'Welche Religionen werden für Prüfung Teil 2 besonders genau gelernt?', correct: 'Buddhismus und Hinduismus', wrong: ['Christentum und Islam', 'Judentum und Christentum'], explanation: 'Die grün markierten Lernziele für Teil 2 betreffen Buddhismus und Hinduismus.' },
  { label: 'Monotheismus', prompt: 'Was bedeutet Monotheismus?', correct: 'Glaube an einen Gott', wrong: ['Glaube an viele Gottheiten', 'Ablehnung jeder religiösen Praxis'], explanation: '„mono“ bedeutet eins oder allein.' },
  { label: 'Polytheismus', prompt: 'Was bedeutet Polytheismus?', correct: 'Glaube an mehrere Gottheiten', wrong: ['Glaube an genau einen Gott', 'Glaube nur an Naturwissenschaft'], explanation: '„poly“ bedeutet viel oder mehrere.' },
  { label: 'abrahamitische Religionen', prompt: 'Welche drei Religionen sind monotheistisch und berufen sich auf Abraham?', correct: 'Judentum, Christentum und Islam', wrong: ['Buddhismus, Hinduismus und Islam', 'Christentum, Buddhismus und Hinduismus'], explanation: 'Judentum, Christentum und Islam werden als abrahamitische Religionen bezeichnet.' },
  { label: 'Verbreitungskarte', prompt: 'Wie liest man eine Karte zur Verbreitung von Religionen richtig?', correct: 'Sie zeigt vereinfachte Schwerpunkte; Religionen leben heute in vielen Ländern.', wrong: ['Jede Farbe bedeutet, dass dort nur eine Religion erlaubt ist.', 'Sie zeigt, dass jede Religion nur in ihrem Ursprungsland vorkommt.'], explanation: 'Religionskarten vereinfachen. In vielen Ländern leben Menschen mit unterschiedlichen Religionen.' },
  { label: 'Buddhismus – Verbreitung', prompt: 'Wo liegen wichtige Verbreitungsschwerpunkte des Buddhismus?', correct: 'In Ost-, Südost- und Teilen Südasiens', wrong: ['Nur in Nordeuropa', 'Ausschliesslich in Südamerika'], explanation: 'Buddhistische Traditionen sind besonders in vielen Teilen Asiens verbreitet und heute weltweit präsent.' },
  { label: 'Hinduismus – Verbreitung', prompt: 'Wo liegt der wichtigste Verbreitungsschwerpunkt des Hinduismus?', correct: 'In Indien und Südasien', wrong: ['In Skandinavien', 'Nur in Nordamerika'], explanation: 'Der Hinduismus entstand in Südasien; die meisten Hindus leben in Indien, daneben gibt es Gemeinschaften weltweit.' },
  { label: 'Dharma-Rad', prompt: 'Welches Zeichen wird im Lernheft dem Buddhismus zugeordnet?', correct: 'Das Dharma-Rad', wrong: ['Der Davidstern', 'Das Kreuz'], explanation: 'Das Dharma-Rad erinnert an Buddhas Lehre und den Weg zur Überwindung des Leidens.' },
  { label: 'Om', prompt: 'Welches Zeichen wird im Lernheft dem Hinduismus zugeordnet?', correct: 'Das Om-Zeichen', wrong: ['Der Halbmond', 'Das Kreuz'], explanation: 'Om ist eine heilige Silbe und ein verbreitetes Zeichen hinduistischer Traditionen.' },
  { label: 'Gottesvorstellung im Buddhismus', prompt: 'Welche Aussage beschreibt den Buddhismus im Schulvergleich am besten?', correct: 'Ein Schöpfergott steht nicht im Zentrum; wichtig sind Lehre und Übung.', wrong: ['Buddhisten glauben zwingend an genau einen Schöpfergott.', 'Buddhismus kennt nur Göttergeschichten und keine Lebensregeln.'], explanation: 'Buddhistische Wege konzentrieren sich auf Erkenntnis, Mitgefühl und die Überwindung des Leidens.' },
  { label: 'Gottesvorstellungen im Hinduismus', prompt: 'Warum lässt sich der Hinduismus nicht mit einem einzigen Satz zu Gott erklären?', correct: 'Es gibt vielfältige Vorstellungen: viele Gottheiten und die eine göttliche Wirklichkeit Brahman.', wrong: ['Weil Hindus überhaupt keine religiösen Vorstellungen haben.', 'Weil alle Hindus nur einen historischen Propheten verehren.'], explanation: 'Hinduistische Traditionen sind vielfältig. Gottheiten können als unterschiedliche Erscheinungsformen des Göttlichen verstanden werden.' },
  { label: 'respektvoll vergleichen', prompt: 'Wie vergleicht man Religionen respektvoll?', correct: 'Man sagt „viele“, „manche“ oder „in dieser Tradition“ und vermeidet Pauschalurteile.', wrong: ['Man behauptet, alle Gläubigen lebten genau gleich.', 'Man bewertet eine Religion als grundsätzlich besser.'], explanation: 'Religionen sind vielfältig; Lernkarten geben Orientierung, beschreiben aber nie jeden Menschen.' },
  { label: 'Glaubensaussage', prompt: 'Welche Formulierung kennzeichnet eine Glaubensaussage?', correct: '„Buddhistinnen und Buddhisten glauben …“', wrong: ['„Naturwissenschaftlich bewiesen ist …“', '„Alle Menschen müssen glauben …“'], explanation: 'Mit Formulierungen wie „nach hinduistischer Überlieferung“ oder „Buddhisten glauben“ unterscheidet man Glauben und überprüfbare Geschichte.' },
  { label: 'Religion und Alltag', prompt: 'Was kann zu einer Religion gehören?', correct: 'Vorstellungen, Werte, Feste, Regeln, Rituale, Gemeinschaft und Sinnfragen', wrong: ['Nur ein Gebäude und sonst nichts', 'Nur eine Landkarte ohne gelebte Bräuche'], explanation: 'Religion zeigt sich in Überzeugungen und im gelebten Alltag.' },
  { label: 'Ursprungsräume', prompt: 'In welcher Weltregion entstanden Buddhismus und Hinduismus?', correct: 'In Südasien', wrong: ['In Skandinavien', 'In Südamerika'], explanation: 'Beide Religionen entstanden in Südasien und verbreiteten sich von dort unterschiedlich weiter.' },
  { label: 'Alter vergleichen', prompt: 'Welche Religion entwickelte sich früher?', correct: 'Hinduistische Traditionen sind älter als der Buddhismus.', wrong: ['Der Buddhismus ist über 10 000 Jahre älter.', 'Beide wurden im selben Jahr gegründet.'], explanation: 'Hinduistische Traditionen reichen mehr als 3 000 Jahre zurück; der Buddhismus entstand vor etwa 2 500 Jahren.' },
  { label: 'religiöse Orte vergleichen', prompt: 'Welche Zuordnung religiöser Orte stimmt?', correct: 'Buddhismus: Tempel/Kloster · Hinduismus: Mandir/Hausaltar', wrong: ['Buddhismus: Synagoge · Hinduismus: Kirche', 'Buddhismus: Moschee · Hinduismus: Kathedrale'], explanation: 'Die Orte unterscheiden sich; Tempel können in beiden Traditionen vorkommen.' },
  { label: 'Schriften vergleichen', prompt: 'Welche Aussage zu den Schriften beider Religionen stimmt?', correct: 'Beide Religionen kennen mehrere wichtige Textsammlungen.', wrong: ['Beide haben genau dasselbe einzelne Buch.', 'Keine der beiden Religionen kennt überlieferte Texte.'], explanation: 'Buddhistische und hinduistische Traditionen besitzen jeweils verschiedene heilige und lehrreiche Texte.' },
  { label: 'Karma vergleichen', prompt: 'Welcher Begriff ist im Buddhismus und Hinduismus wichtig?', correct: 'Karma – Handlungen haben Folgen', wrong: ['Dreifaltigkeit', 'Hidschra'], explanation: 'Beide Traditionen sprechen von Karma, erklären es aber innerhalb ihrer eigenen Lehren.' },
];

const buddhismFacts: Fact[] = [
  { label: 'Ursprung des Buddhismus', prompt: 'Wo entstand der Buddhismus?', correct: 'In Nordindien vor ungefähr 2 500 Jahren', wrong: ['In Nordeuropa vor 500 Jahren', 'In Amerika vor ungefähr 1 000 Jahren'], explanation: 'Die buddhistische Tradition geht auf Siddhartha Gautama im antiken Nordindien zurück.' },
  { label: 'Buddha', prompt: 'Was bedeutet der Titel „Buddha“?', correct: 'Der Erwachte oder Erleuchtete', wrong: ['Der König aller Tempel', 'Der Schöpfer der Welt'], explanation: 'Buddha ist ein Ehrentitel und bedeutet „der Erwachte“.' },
  { label: 'Siddhartha Gautama', prompt: 'Wer war Siddhartha Gautama?', correct: 'Ein Lehrer aus Nordindien, auf dessen Erkenntnisse der Buddhismus zurückgeht', wrong: ['Ein hinduistischer Schöpfergott', 'Ein römischer Kaiser'], explanation: 'Siddhartha Gautama wurde nach seiner Erleuchtung Buddha genannt.' },
  { label: 'kein zentraler Schöpfergott', prompt: 'Welche Rolle spielt ein Schöpfergott im Buddhismus?', correct: 'Ein Schöpfergott steht nicht im Zentrum der buddhistischen Lehre.', wrong: ['Buddha gilt in allen Schulen als Schöpfergott.', 'Jeder Tempel verehrt zwingend denselben allmächtigen Gott.'], explanation: 'Im Zentrum stehen Buddhas Lehre, die eigene Übung und der Weg aus dem Leiden.' },
  { label: 'Tempel und Kloster', prompt: 'Welche Orte gehören häufig zum Buddhismus?', correct: 'Tempel und Kloster', wrong: ['Kirche und Synagoge', 'Moschee und Kathedrale'], explanation: 'Buddhistische Gemeinschaften treffen sich je nach Tradition in Tempeln, Klöstern oder Meditationszentren.' },
  { label: 'Stupa', prompt: 'Was ist eine Stupa?', correct: 'Ein buddhistisches Bauwerk, das an Buddha und seine Lehre erinnert', wrong: ['Ein jüdisches Gebetbuch', 'Eine christliche Kanzel'], explanation: 'Stupas können Reliquien enthalten und sind Orte der Erinnerung und Verehrung.' },
  { label: 'heilige Texte', prompt: 'Welche Aussage zu buddhistischen Schriften stimmt?', correct: 'Es gibt verschiedene Sammlungen; eine alte Sammlung heisst Tripitaka oder Pali-Kanon.', wrong: ['Alle Buddhisten benutzen nur die Bibel.', 'Buddhismus hat grundsätzlich keine überlieferten Texte.'], explanation: 'Buddhistische Schulen überliefern unterschiedliche Textsammlungen. Der Pali-Kanon ist besonders alt.' },
  { label: 'Dharma', prompt: 'Was bedeutet Dharma im Buddhismus?', correct: 'Die Lehre Buddhas und der Weg der Übung', wrong: ['Ein Tempelturm', 'Ein Festessen nach Sonnenuntergang'], explanation: 'Dharma bezeichnet Buddhas Lehre; das Dharma-Rad symbolisiert ihre Weitergabe.' },
  { label: 'Sangha', prompt: 'Was bedeutet Sangha?', correct: 'Die buddhistische Gemeinschaft', wrong: ['Ein hinduistischer Fluss', 'Eine christliche Konfession'], explanation: 'Sangha kann besonders die Gemeinschaft der Ordinierten, weiter gefasst auch die buddhistische Gemeinschaft meinen.' },
  { label: 'Meditation', prompt: 'Wozu dient Meditation in vielen buddhistischen Traditionen?', correct: 'Achtsamkeit, Sammlung und Einsicht zu üben', wrong: ['Reichtum möglichst schnell zu vermehren', 'Einen Schöpfergott sichtbar zu machen'], explanation: 'Meditation hilft, den Geist zu beobachten und heilsame Haltungen zu entwickeln.' },
  { label: 'fünf ethische Regeln', prompt: 'Was ist eine der fünf buddhistischen Übungsregeln für Laien?', correct: 'Lebewesen nicht absichtlich verletzen', wrong: ['Andere zum eigenen Glauben zwingen', 'Immer möglichst viele Dinge besitzen'], explanation: 'Die fünf Regeln fördern unter anderem Gewaltlosigkeit, Ehrlichkeit und einen klaren Geist.' },
  { label: 'Karma', prompt: 'Was bedeutet Karma im buddhistischen Zusammenhang?', correct: 'Absichtsvolle Handlungen haben Folgen.', wrong: ['Jedes Ereignis ist eine unveränderbare Strafe.', 'Nur der Besitz aus einem früheren Leben zählt.'], explanation: 'Karma meint die Wirkung absichtsvoller Handlungen, nicht ein starres Schicksal.' },
  { label: 'Wiedergeburt', prompt: 'Was gehört in vielen buddhistischen Traditionen zum Kreislauf des Daseins?', correct: 'Wiedergeburt', wrong: ['Die Dreifaltigkeit', 'Die einmalige Pilgerfahrt nach Mekka'], explanation: 'Der Kreislauf von Werden und Wiedergeburt wird Samsara genannt.' },
  { label: 'Nirvana', prompt: 'Was bezeichnet Nirvana?', correct: 'Das Erlöschen von Gier, Hass und Verblendung und damit die Befreiung vom Leiden', wrong: ['Einen besonders grossen Tempel', 'Die Geburt eines Schöpfergottes'], explanation: 'Nirvana ist das Ziel des buddhistischen Weges: Befreiung vom Leiden und vom Kreislauf des Daseins.' },
  { label: 'Vesakh', prompt: 'Welches wichtige buddhistische Fest erinnert an Buddha?', correct: 'Vesakh (auch Wesak)', wrong: ['Weihnachten', 'Jom Kippur'], explanation: 'Vesakh erinnert je nach Tradition an Geburt, Erwachen und Tod Buddhas.' },
  { label: 'Mönche und Nonnen', prompt: 'Wie leben buddhistische Mönche und Nonnen häufig?', correct: 'In einer Gemeinschaft mit Regeln, Meditation, Lernen und einfacher Lebensweise', wrong: ['Als Könige mit möglichst viel Besitz', 'Ohne jede Regel oder Gemeinschaft'], explanation: 'Ordensgemeinschaften bewahren und üben Buddhas Lehre; ihre Lebensformen unterscheiden sich je nach Tradition.' },
  { label: 'Mitgefühl', prompt: 'Welche Haltung ist im Buddhismus besonders wichtig?', correct: 'Mitgefühl mit Lebewesen', wrong: ['Gleichgültigkeit gegenüber Leid', 'Rache als oberstes Ziel'], explanation: 'Mitgefühl und das Vermeiden von Schaden gehören zu zentralen buddhistischen Haltungen.' },
  { label: 'Lotus', prompt: 'Was kann die Lotusblüte im Buddhismus symbolisieren?', correct: 'Reinheit und Erwachen trotz schwieriger Bedingungen', wrong: ['Militärische Macht', 'Den Besitz eines Landes'], explanation: 'Wie eine Blüte aus schlammigem Wasser wachsen kann, steht der Lotus für geistige Entwicklung.' },
  { label: 'Gaben', prompt: 'Warum bringen manche Buddhisten in Tempeln Blumen, Licht oder Räucherwerk dar?', correct: 'Als Zeichen von Respekt, Dankbarkeit und Erinnerung an die Lehre', wrong: ['Um Buddha Nahrung als Schöpfergott zu geben', 'Weil nur teure Gaben zur Erleuchtung führen'], explanation: 'Gaben sind symbolische Handlungen; Praxis und Bedeutung unterscheiden sich nach Tradition.' },
  { label: 'Vielfalt des Buddhismus', prompt: 'Welche Aussage über buddhistische Traditionen ist richtig?', correct: 'Theravada, Mahayana und Vajrayana setzen unterschiedliche Schwerpunkte.', wrong: ['Alle Buddhisten üben überall genau gleich.', 'Es gibt nur eine buddhistische Gemeinschaft weltweit.'], explanation: 'Der Buddhismus ist vielfältig; Lehre, Rituale und Alltagsformen unterscheiden sich regional.' },
];

const buddhaFacts: Fact[] = [
  { label: 'Geburt Siddharthas', prompt: 'Wie begann Siddhartha Gautamas Leben nach der Überlieferung?', correct: 'Er wurde als Sohn einer vornehmen Familie geboren und lebte zunächst geschützt.', wrong: ['Er wurde als römischer Soldat geboren.', 'Er lebte von Anfang an allein in einer Höhle.'], explanation: 'Die Erzählung beschreibt Siddhartha als privilegierten jungen Mann, der Leid zunächst kaum kannte.' },
  { label: 'Lumbini', prompt: 'Welcher Ort gilt traditionell als Geburtsort Siddharthas?', correct: 'Lumbini im heutigen Nepal', wrong: ['Rom in Italien', 'Jerusalem in Israel'], explanation: 'Lumbini liegt im heutigen Nepal nahe der indischen Grenze.' },
  { label: 'Palastleben', prompt: 'Warum liess Siddharthas Vater ihn nach der Überlieferung geschützt im Palast leben?', correct: 'Er wollte Leid, Krankheit, Alter und Tod von ihm fernhalten.', wrong: ['Er wollte ihn auf eine Seereise vorbereiten.', 'Er verbot ihm jedes Lernen.'], explanation: 'Das geschützte Leben erklärt, warum die späteren Begegnungen Siddhartha so tief bewegten.' },
  { label: 'vier Begegnungen', prompt: 'Was sah Siddhartha bei den vier Begegnungen?', correct: 'Einen alten Menschen, einen Kranken, einen Toten und einen religiös Suchenden', wrong: ['Einen König, einen Händler, einen Soldaten und einen Bauern', 'Vier verschiedene Tempel'], explanation: 'Die Begegnungen zeigten ihm Leid und zugleich die Möglichkeit eines geistigen Weges.' },
  { label: 'Auszug', prompt: 'Was tat Siddhartha nach den Begegnungen mit dem Leid?', correct: 'Er verliess sein bequemes Leben, um einen Weg aus dem Leiden zu suchen.', wrong: ['Er wurde ein reicher Händler.', 'Er baute sofort einen Palast.'], explanation: 'Er gab sein privilegiertes Leben auf und begann eine religiöse Suche.' },
  { label: 'Askese', prompt: 'Was versuchte Siddhartha zuerst auf seiner Suche?', correct: 'Strenge Askese und extremes Fasten', wrong: ['Luxus und möglichst viel Besitz', 'Eine militärische Ausbildung'], explanation: 'Er merkte, dass extreme Selbstquälerei nicht zur befreienden Erkenntnis führte.' },
  { label: 'Mittlerer Weg', prompt: 'Was meint der „Mittlere Weg“?', correct: 'Weder Luxus noch extreme Selbstquälerei', wrong: ['Immer den geografisch mittleren Weg wählen', 'Keine Entscheidungen treffen'], explanation: 'Siddhartha erkannte, dass beide Extreme nicht hilfreich sind.' },
  { label: 'Bodhi-Baum', prompt: 'Wo erlangte Siddhartha nach der Überlieferung die Erleuchtung?', correct: 'Beim Meditieren unter dem Bodhi-Baum', wrong: ['Auf einem Schiff im Mittelmeer', 'In einem Königspalast in Europa'], explanation: 'Unter dem Bodhi-Baum wurde Siddhartha zum Buddha, zum Erwachten.' },
  { label: 'Erwachen', prompt: 'Was erkannte Buddha beim Erwachen?', correct: 'Die Ursachen des Leidens und einen Weg zu seiner Überwindung', wrong: ['Wie man ein Reich erobert', 'Dass Besitz jedes Problem löst'], explanation: 'Diese Einsicht wird in den vier edlen Wahrheiten zusammengefasst.' },
  { label: 'erste edle Wahrheit', prompt: 'Was sagt die erste edle Wahrheit?', correct: 'Das Leben ist mit Leiden und Unzufriedenheit verbunden.', wrong: ['Jeder Mensch ist immer glücklich.', 'Leiden existiert nur in Träumen.'], explanation: 'Buddha begann mit der ehrlichen Beobachtung, dass Leben auch Leid und Unzufriedenheit enthält.' },
  { label: 'zweite edle Wahrheit', prompt: 'Was nennt die zweite edle Wahrheit als Ursache des Leidens?', correct: 'Gier, Begehren, Hass und Unwissenheit', wrong: ['Nur schlechtes Wetter', 'Das Lernen und Nachdenken'], explanation: 'Festhalten und Verlangen lassen Unzufriedenheit entstehen.' },
  { label: 'dritte edle Wahrheit', prompt: 'Was sagt die dritte edle Wahrheit?', correct: 'Leiden kann überwunden werden, wenn seine Ursachen enden.', wrong: ['Leiden muss absichtlich vergrössert werden.', 'Kein Mensch kann etwas verändern.'], explanation: 'Befreiung ist möglich, wenn Gier, Hass und Unwissenheit überwunden werden.' },
  { label: 'vierte edle Wahrheit', prompt: 'Was zeigt die vierte edle Wahrheit?', correct: 'Der achtfache Pfad ist der Weg zur Überwindung des Leidens.', wrong: ['Acht Tempel müssen gebaut werden.', 'Nur Reichtum führt zur Befreiung.'], explanation: 'Der achtfache Pfad verbindet Einsicht, ethisches Handeln und geistige Übung.' },
  { label: 'achtfacher Pfad', prompt: 'Was gehört zum achtfachen Pfad?', correct: 'Zum Beispiel rechte Rede, rechtes Handeln und rechte Achtsamkeit', wrong: ['Sieg, Besitz und Ruhm', 'Acht vorgeschriebene Gottheiten'], explanation: 'Der Pfad umfasst rechte Sicht, Absicht, Rede, Handeln, Lebensunterhalt, Bemühen, Achtsamkeit und Sammlung.' },
  { label: 'Buddhas Lebensende', prompt: 'Wie endete Buddhas Leben nach der Überlieferung?', correct: 'Er lehrte viele Jahre und starb im hohen Alter; er ging ins endgültige Nirvana ein.', wrong: ['Er wurde Kaiser von Indien.', 'Er kehrte als Prinz in ein Luxusleben zurück.'], explanation: 'Die Überlieferung berichtet, dass Buddha bis ins hohe Alter lehrte und etwa 80-jährig starb.' },
  { label: 'Siddharthas Familie', prompt: 'Was liess Siddhartha bei seinem Aufbruch nach der Überlieferung zurück?', correct: 'Sein privilegiertes Leben sowie Frau und Sohn', wrong: ['Eine Armee und ein erobertes Reich', 'Ein buddhistisches Kloster, das er schon als Kind leitete'], explanation: 'Die Erzählung betont, wie radikal sein Entschluss zur Suche nach Befreiung war.' },
  { label: 'Alter beim Aufbruch', prompt: 'Wie alt war Siddhartha ungefähr, als er den Palast verliess?', correct: 'Etwa 29 Jahre', wrong: ['Etwa 9 Jahre', 'Etwa 79 Jahre'], explanation: 'Traditionelle Lebensgeschichten nennen ungefähr 29 Jahre für den Beginn seiner Suche.' },
  { label: 'erste Lehrrede', prompt: 'Was geschah nach Buddhas Erwachen?', correct: 'Er hielt bei Sarnath seine erste Lehrrede.', wrong: ['Er verbot jede Weitergabe seiner Erkenntnis.', 'Er gründete ein Königreich in Rom.'], explanation: 'Die erste Lehrrede wird sinnbildlich „das Rad der Lehre in Bewegung setzen“ genannt.' },
  { label: 'drei Kostbarkeiten', prompt: 'Was sind die drei Kostbarkeiten im Buddhismus?', correct: 'Buddha, Dharma und Sangha', wrong: ['Brahma, Vishnu und Shiva', 'Tora, Bibel und Koran'], explanation: 'Buddha ist der Lehrer, Dharma die Lehre und Sangha die Gemeinschaft.' },
  { label: 'eigene Worte zu Buddha', prompt: 'Welche Kurzantwort fasst Buddhas Lebensweg sinnvoll zusammen?', correct: 'Er begegnete dem Leid, suchte einen Weg, erwachte und gab seine Erkenntnis weiter.', wrong: ['Er erbte ein Reich und suchte vor allem Reichtum.', 'Er erklärte Leiden für völlig bedeutungslos.'], explanation: 'Eine gute freie Erzählung zeigt Ursache, Suche, Erkenntnis und Weitergabe.' },
];

const hinduismFacts: Fact[] = [
  { label: 'Ursprung des Hinduismus', prompt: 'Wo und wann entstand der Hinduismus?', correct: 'In Südasien über einen langen Zeitraum vor mehr als 3 000 Jahren', wrong: ['In Nordeuropa vor 300 Jahren', 'An einem einzigen Tag in Amerika'], explanation: 'Der Hinduismus entwickelte sich über lange Zeit in Südasien und hat keinen einzelnen Gründungstag.' },
  { label: 'kein einzelner Gründer', prompt: 'Wer gründete den Hinduismus?', correct: 'Es gibt keinen einzelnen Gründer.', wrong: ['Buddha allein', 'Ein römischer Kaiser'], explanation: 'Hinduistische Traditionen entwickelten sich über viele Jahrhunderte.' },
  { label: 'Sanatana Dharma', prompt: 'Wie nennen viele Hindus ihre Religion auch?', correct: 'Sanatana Dharma – die ewige Ordnung oder der ewige Weg', wrong: ['Sangha – die Klostergemeinschaft', 'Trinität – Vater, Sohn und Heiliger Geist'], explanation: 'Sanatana Dharma ist eine verbreitete Selbstbezeichnung hinduistischer Traditionen.' },
  { label: 'Brahman', prompt: 'Was bezeichnet Brahman im Hinduismus?', correct: 'Die höchste, alles durchdringende göttliche Wirklichkeit', wrong: ['Nur einen Tempel in Indien', 'Eine buddhistische Mönchsregel'], explanation: 'Brahman ist nicht dasselbe wie der Gott Brahma: Brahman bezeichnet die umfassende göttliche Wirklichkeit.' },
  { label: 'Atman', prompt: 'Was bezeichnet Atman in vielen hinduistischen Lehren?', correct: 'Das innerste Selbst oder die Seele eines Lebewesens', wrong: ['Ein Fest im Frühling', 'Eine heilige Stadt ausserhalb Asiens'], explanation: 'Viele Lehren fragen nach dem Verhältnis von Atman und Brahman.' },
  { label: 'Mandir', prompt: 'Wie heisst ein hinduistischer Tempel?', correct: 'Mandir', wrong: ['Synagoge', 'Moschee'], explanation: 'Ein hinduistischer Tempel wird häufig Mandir genannt.' },
  { label: 'Hausaltar', prompt: 'Wo findet hinduistische Verehrung ausser im Tempel statt?', correct: 'Oft auch zu Hause an einem Hausaltar', wrong: ['Nur in Sportstadien', 'Ausschliesslich in Kirchen'], explanation: 'Viele Familien haben zu Hause einen kleinen Schrein oder Altar für die Puja.' },
  { label: 'heilige Schriften', prompt: 'Welche Texte gehören zu den heiligen Schriften des Hinduismus?', correct: 'Zum Beispiel Veden, Bhagavad Gita und Upanishaden', wrong: ['Nur die Tora', 'Nur der Koran'], explanation: 'Der Hinduismus kennt verschiedene alte und wichtige Textsammlungen.' },
  { label: 'Puja', prompt: 'Was ist eine Puja?', correct: 'Eine hinduistische Verehrungszeremonie mit Gebeten und Gaben', wrong: ['Eine buddhistische Bauform', 'Ein christliches Glaubensbekenntnis'], explanation: 'Bei einer Puja können Licht, Blumen, Wasser, Speisen oder Räucherwerk dargebracht werden.' },
  { label: 'Dharma im Hinduismus', prompt: 'Was bedeutet Dharma im hinduistischen Zusammenhang?', correct: 'Pflicht, verantwortliches Handeln und die Ordnung des Lebens', wrong: ['Möglichst viel Besitz sammeln', 'Jede Regel ablehnen'], explanation: 'Dharma beschreibt ein verantwortliches Leben entsprechend Aufgabe, Lebensphase und Ordnung.' },
  { label: 'Karma im Hinduismus', prompt: 'Was bedeutet Karma im Hinduismus?', correct: 'Handlungen haben Folgen für dieses und weitere Leben.', wrong: ['Alles ist reiner Zufall ohne Folgen.', 'Nur Rituale im Tempel zählen.'], explanation: 'Karma verbindet Handeln und Folgen im Kreislauf der Wiedergeburten.' },
  { label: 'Samsara', prompt: 'Was ist Samsara?', correct: 'Der Kreislauf von Geburt, Tod und Wiedergeburt', wrong: ['Ein heiliges Buch', 'Ein Tempelturm'], explanation: 'Samsara bezeichnet den Kreislauf, aus dem Befreiung gesucht wird.' },
  { label: 'Moksha', prompt: 'Was bedeutet Moksha?', correct: 'Befreiung aus dem Kreislauf der Wiedergeburten', wrong: ['Die Gründung eines neuen Tempels', 'Eine Pflichtreise nach Rom'], explanation: 'Moksha ist in vielen hinduistischen Traditionen ein zentrales religiöses Ziel.' },
  { label: 'Diwali', prompt: 'Was wird beim Fest Diwali besonders sichtbar?', correct: 'Lichter als Zeichen für den Sieg des Guten und des Lichts', wrong: ['Das Ende jeder religiösen Feier', 'Eine Fastenzeit ohne Licht'], explanation: 'Diwali ist ein wichtiges Lichterfest; seine Geschichten und Bräuche unterscheiden sich regional.' },
  { label: 'Ganges', prompt: 'Welche Bedeutung hat der Ganges für viele Hindus?', correct: 'Er gilt als heiliger Fluss und als wichtiges Pilgerziel.', wrong: ['Er ist ausschliesslich ein buddhistischer Tempel.', 'Er liegt in Südamerika.'], explanation: 'Viele Gläubige pilgern an den Ganges und verbinden sein Wasser mit Reinigung und Segen.' },
  { label: 'heilige Kuh', prompt: 'Warum behandeln viele Hindus Kühe mit besonderem Respekt?', correct: 'Die Kuh gilt als Symbol für Leben, Fürsorge und Gewaltlosigkeit.', wrong: ['Weil alle Kühe als dieselbe einzelne Gottheit gelten.', 'Weil Kühe nur in Tempeln leben dürfen.'], explanation: 'Der besondere Respekt hat religiöse und kulturelle Gründe; Praktiken unterscheiden sich.' },
  { label: 'Vegetarismus', prompt: 'Welche Aussage über Ernährung im Hinduismus ist sachlich?', correct: 'Viele Hindus leben vegetarisch, aber nicht alle.', wrong: ['Alle Hindus essen weltweit genau gleich.', 'Vegetarische Ernährung ist im Hinduismus verboten.'], explanation: 'Gewaltlosigkeit und Reinheitsvorstellungen beeinflussen die Ernährung, doch die Praxis ist vielfältig.' },
  { label: 'Holi', prompt: 'Wofür ist das hinduistische Fest Holi bekannt?', correct: 'Für Farben, Frühlingsfreude und Geschichten vom Sieg des Guten', wrong: ['Für acht Tage ohne Licht', 'Für die Pilgerfahrt nach Mekka'], explanation: 'Holi wird regional verschieden gefeiert und ist besonders für farbiges Pulver bekannt.' },
  { label: 'Yoga', prompt: 'Was kann Yoga im hinduistischen Zusammenhang bedeuten?', correct: 'Einen geistigen und körperlichen Übungsweg zur Sammlung und Erkenntnis', wrong: ['Nur einen modernen Wettbewerb', 'Eine einzelne Tempelgottheit'], explanation: 'Yoga umfasst mehr als Körperübungen und hat vielfältige philosophische und religiöse Traditionen.' },
  { label: 'Om als Silbe', prompt: 'Was ist Om genauer?', correct: 'Eine heilige Silbe, die bei Gebet und Meditation gesprochen werden kann', wrong: ['Der Name eines einzigen Tempels', 'Ein Gesetzbuch des römischen Reiches'], explanation: 'Om wird geschrieben, gesprochen und gesungen und symbolisiert in vielen Lehren die umfassende Wirklichkeit.' },
];

const deityFacts: Fact[] = [
  { label: 'Brahma', prompt: 'Wie kann man Brahma beschreiben?', correct: 'Brahma gilt als Schöpfer und wird oft mit vier Köpfen dargestellt.', wrong: ['Brahma ist der elefantenköpfige Gott der Anfänge.', 'Brahma ist der historische Gründer des Buddhismus.'], explanation: 'Brahma gehört mit Vishnu und Shiva zu einer bekannten Dreierdarstellung göttlicher Aufgaben.' },
  { label: 'Vishnu', prompt: 'Wie kann man Vishnu beschreiben?', correct: 'Vishnu gilt als Bewahrer der Welt und erscheint der Überlieferung nach in verschiedenen Avataren.', wrong: ['Vishnu ist ausschliesslich der Gott des Feuers.', 'Vishnu ist ein buddhistisches Gebetbuch.'], explanation: 'Rama und Krishna werden in vielen Traditionen als Avatare Vishnus verstanden.' },
  { label: 'Shiva', prompt: 'Wie kann man Shiva beschreiben?', correct: 'Shiva steht für Zerstörung und Erneuerung beziehungsweise Verwandlung.', wrong: ['Shiva ist nur für Handel und Geld zuständig.', 'Shiva gründete vor 500 Jahren eine Kirche.'], explanation: 'Shivas zerstörende Kraft bedeutet auch Veränderung und Neubeginn.' },
  { label: 'Ganesha', prompt: 'Woran erkennt man Ganesha und wofür wird er verehrt?', correct: 'Am Elefantenkopf; er gilt als Helfer bei Neuanfängen und Hindernissen.', wrong: ['Am Davidstern; er gilt als König Israels.', 'An Flügeln; er gilt als christlicher Engel.'], explanation: 'Ganesha ist eine besonders bekannte hinduistische Gottheit.' },
  { label: 'Lakshmi', prompt: 'Wofür steht Lakshmi?', correct: 'Glück, Wohlstand und Segen', wrong: ['Krieg ohne Schutzfunktion', 'Die buddhistische Klosterordnung'], explanation: 'Lakshmi wird oft mit Lotusblüten dargestellt und besonders an Diwali verehrt.' },
  { label: 'Saraswati', prompt: 'Wofür steht Saraswati?', correct: 'Wissen, Lernen, Sprache, Musik und Kunst', wrong: ['Ausschliesslich Zerstörung', 'Den Gebetsruf in einer Moschee'], explanation: 'Saraswati wird häufig mit einem Musikinstrument und Büchern dargestellt.' },
  { label: 'Parvati', prompt: 'Wie wird Parvati häufig beschrieben?', correct: 'Als Göttin der Liebe, Familie und weiblichen Kraft', wrong: ['Als männlicher Gott des Meeres', 'Als Gründerin des Buddhismus'], explanation: 'Parvati ist Shivas Gefährtin und wird in verschiedenen Formen verehrt.' },
  { label: 'Durga', prompt: 'Wofür steht Durga?', correct: 'Für schützende Kraft und den Sieg über das Böse', wrong: ['Nur für stilles Lesen', 'Für die christliche Taufe'], explanation: 'Durga wird oft kraftvoll, mit mehreren Armen und auf einem Löwen oder Tiger dargestellt.' },
  { label: 'Kali', prompt: 'Wie lässt sich Kali respektvoll beschreiben?', correct: 'Als kraftvolle Göttin, die zerstörerische Kräfte und Unwissenheit überwindet', wrong: ['Als böse Figur ohne religiöse Bedeutung', 'Als buddhistische Nonne'], explanation: 'Ihre furchterregende Darstellung symbolisiert unter anderem Macht, Zeit und radikale Veränderung.' },
  { label: 'Krishna', prompt: 'Wie kann man Krishna beschreiben?', correct: 'Als Avatar Vishnus, Lehrer der Bhagavad Gita und oft als Flötenspieler', wrong: ['Als Gründer des Islam', 'Als Gott mit Elefantenkopf'], explanation: 'Krishna ist eine sehr verehrte Gottheit; Geschichten erzählen von seiner Kindheit, Liebe und Lehre.' },
  { label: 'Rama', prompt: 'Wer ist Rama?', correct: 'Ein Avatar Vishnus und Held des Epos Ramayana', wrong: ['Der Verfasser der Tora', 'Ein buddhistischer Tempel'], explanation: 'Rama gilt als Vorbild für Pflichterfüllung und gerechtes Handeln.' },
  { label: 'Hanuman', prompt: 'Wofür ist Hanuman bekannt?', correct: 'Für Mut, Kraft und treue Hingabe an Rama', wrong: ['Für die Erfindung des Dharma-Rads', 'Als Oberhaupt der katholischen Kirche'], explanation: 'Der affengestaltige Hanuman ist eine wichtige Figur im Ramayana.' },
  { label: 'Avatar', prompt: 'Was bedeutet Avatar im hinduistischen Zusammenhang?', correct: 'Eine Erscheinungsform oder Herabkunft einer Gottheit auf der Erde', wrong: ['Nur ein Bild im Internet', 'Ein buddhistischer Klostervorsteher'], explanation: 'Besonders von Vishnu werden verschiedene Avatare erzählt, darunter Rama und Krishna.' },
  { label: 'Darstellungsmerkmale', prompt: 'Warum tragen hinduistische Götterbilder oft besondere Gegenstände oder mehrere Arme?', correct: 'Die Merkmale symbolisieren Kräfte, Aufgaben und Geschichten der Gottheit.', wrong: ['Sie sollen beweisen, dass alle Hindus gleich denken.', 'Sie haben keine Bedeutung und sind nur zufällig.'], explanation: 'Attribute wie Lotus, Dreizack oder Musikinstrument helfen, Gottheiten und ihre Bedeutungen zu erkennen.' },
  { label: 'eine Gottheit beschreiben', prompt: 'Was gehört zu einer guten Beschreibung einer hinduistischen Gottheit?', correct: 'Name, Erkennungsmerkmal, Aufgabe oder Bedeutung und möglichst eine zugehörige Geschichte', wrong: ['Nur die Farbe des Bildes', 'Ein Urteil darüber, ob die Religion richtig ist'], explanation: 'So entsteht eine sachliche Antwort in eigenen Worten, wie sie das Lernziel verlangt.' },
  { label: 'Trimurti', prompt: 'Welche drei Gottheiten werden oft als Trimurti zusammen dargestellt?', correct: 'Brahma, Vishnu und Shiva', wrong: ['Buddha, Jesus und Mohammed', 'Ganesha, Abraham und Mose'], explanation: 'Die Trimurti verbindet bildhaft Schöpfung, Bewahrung und Verwandlung.' },
  { label: 'Murti', prompt: 'Was ist eine Murti?', correct: 'Eine geweihte Darstellung einer Gottheit, die bei der Verehrung gegenwärtig gedacht wird', wrong: ['Ein buddhistisches Regelbuch', 'Nur eine bedeutungslose Dekoration'], explanation: 'Eine Murti kann im Tempel oder Hausaltar Mittelpunkt einer Puja sein.' },
  { label: 'Vahana', prompt: 'Was ist ein Vahana bei hinduistischen Gottheiten?', correct: 'Ein Reit- oder Begleittier mit symbolischer Bedeutung', wrong: ['Eine heilige Schrift', 'Ein Gebetshaus'], explanation: 'Zum Beispiel wird Ganesha oft mit einer Maus und Durga mit Löwe oder Tiger dargestellt.' },
  { label: 'persönliche Verehrung', prompt: 'Müssen alle Hindus dieselbe Gottheit besonders verehren?', correct: 'Nein, Familien und Traditionen können unterschiedliche Gottheiten in den Mittelpunkt stellen.', wrong: ['Ja, überall ist nur dieselbe Gottheit erlaubt.', 'Nein, denn Gottheiten dürfen im Hinduismus nie verehrt werden.'], explanation: 'Die Vielfalt persönlicher und regionaler Verehrung ist ein wichtiges Merkmal des Hinduismus.' },
  { label: 'Göttinnen und Götter', prompt: 'Welche Aussage über weibliche und männliche Formen des Göttlichen stimmt?', correct: 'Im Hinduismus werden Göttinnen und Götter als kraftvolle Formen des Göttlichen verehrt.', wrong: ['Nur männliche Darstellungen sind erlaubt.', 'Göttinnen kommen in hinduistischen Traditionen nicht vor.'], explanation: 'Göttinnen wie Lakshmi, Saraswati, Durga, Parvati und Kali sind in vielen Traditionen zentral.' },
];

export const questions: Question[] = [
  ...questionsFromFacts('Überblick & Vergleich', 'u', overviewFacts),
  ...questionsFromFacts('Buddhismus', 'b', buddhismFacts),
  ...questionsFromFacts('Buddhas Leben & Lehre', 'l', buddhaFacts),
  ...questionsFromFacts('Hinduismus', 'h', hinduismFacts),
  ...questionsFromFacts('Hinduistische Gottheiten', 'g', deityFacts),
];

export function shuffleIndices(length: number, random: () => number = Math.random): number[] {
  const result = Array.from({ length }, (_, index) => index);
  for (let index = result.length - 1; index > 0; index -= 1) {
    const target = Math.floor(random() * (index + 1));
    [result[index], result[target]] = [result[target], result[index]];
  }
  return result;
}

function practiceWeight(stat?: ItemStat): number {
  if (!stat?.attempts) return 4;
  const accuracy = stat.correct / stat.attempts;
  return 1 + (1 - accuracy) * 7 + (accuracy < 0.8 ? 2 : 0) + Math.max(0, 2 - stat.attempts);
}

export function buildAdaptiveRound(filter: Topic | 'Alle', items: Record<string, ItemStat>, options: { onlyIds?: string[]; size?: number; random?: () => number } = {}): string[] {
  const random = options.random ?? Math.random;
  const allowedIds = options.onlyIds ? new Set(options.onlyIds) : null;
  const pool = questions.filter((question) => (filter === 'Alle' || question.topic === filter) && (!allowedIds || allowedIds.has(question.id)));
  const size = Math.min(options.size ?? (filter === 'Alle' ? 15 : 12), pool.length);
  return pool.map((question) => ({ id: question.id, rank: -Math.log(Math.max(random(), Number.EPSILON)) / practiceWeight(items[question.id]) })).sort((left, right) => left.rank - right.rank).slice(0, size).map(({ id }) => id);
}
