export type Topic = 'Grundwissen' | 'Christentum' | 'Islam' | 'Judentum' | 'Gebäude & Schriften';
export type Question = { id: string; topic: Topic; prompt: string; options: string[]; answer: number; explanation: string };
export type ItemStat = { attempts: number; correct: number };

export const topics: Topic[] = ['Grundwissen', 'Christentum', 'Islam', 'Judentum', 'Gebäude & Schriften'];

export const questions: Question[] = [
  { id: 'g1', topic: 'Grundwissen', prompt: 'Welche fünf Weltreligionen stehen im Lernheft?', options: ['Christentum, Islam, Judentum, Hinduismus, Buddhismus', 'Christentum, Islam, Sikhismus, Taoismus, Jainismus', 'Judentum, Islam, Schintoismus, Bahai, Buddhismus'], answer: 0, explanation: 'Für den Überblick kennst du alle fünf. In Prüfung Teil 1 lernst du Christentum, Islam und Judentum genauer.' },
  { id: 'g2', topic: 'Grundwissen', prompt: 'Was bedeutet Monotheismus?', options: ['Glaube an einen Gott', 'Glaube an viele Gottheiten', 'Keine religiöse Überzeugung'], answer: 0, explanation: 'mono bedeutet eins oder allein.' },
  { id: 'g3', topic: 'Grundwissen', prompt: 'Was bedeutet Polytheismus?', options: ['Glaube an viele Gottheiten', 'Glaube an einen Gott', 'Glaube nur an Engel'], answer: 0, explanation: 'poly bedeutet viel oder mehrere.' },
  { id: 'g4', topic: 'Grundwissen', prompt: 'Welche drei Religionen sind monotheistisch?', options: ['Judentum, Christentum und Islam', 'Hinduismus, Buddhismus und Islam', 'Christentum, Buddhismus und Hinduismus'], answer: 0, explanation: 'Judentum, Christentum und Islam glauben an einen Gott.' },
  { id: 'g5', topic: 'Grundwissen', prompt: 'Welche Aussage zur Verbreitung ist am besten?', options: ['Religionen kommen heute oft in vielen Ländern vor; Karten zeigen Schwerpunkte.', 'Jede Religion gibt es nur in einem Land.', 'In Europa gibt es nur Christentum.'], answer: 0, explanation: 'Menschen und Religionen sind weltweit vielfältig. Schulbuchkarten vereinfachen und zeigen Schwerpunkte.' },
  { id: 'g6', topic: 'Grundwissen', prompt: 'Welches Symbol ordnet das Lernheft dem Buddhismus zu?', options: ['Dharma-Rad', 'Kreuz', 'Davidstern'], answer: 0, explanation: 'Das Rad steht unter anderem für die Lehre und den Weg Buddhas.' },
  { id: 'g7', topic: 'Grundwissen', prompt: 'Welches Symbol ordnet das Lernheft dem Hinduismus zu?', options: ['Om-Zeichen', 'Halbmond', 'Kreuz'], answer: 0, explanation: 'Om ist eine heilige Silbe und ein verbreitetes Zeichen hinduistischer Traditionen.' },
  { id: 'g8', topic: 'Grundwissen', prompt: 'Wozu können Religionen Menschen helfen?', options: ['Sinnfragen bedenken, Gemeinschaft erleben und Werte finden', 'Jede wissenschaftliche Frage endgültig lösen', 'Alle Menschen gleich denken lassen'], answer: 0, explanation: 'Religion kann Halt, Gemeinschaft, Rituale und Antworten auf Sinnfragen geben.' },
  { id: 'g9', topic: 'Grundwissen', prompt: 'Welche drei Religionen werden in Prüfung Teil 1 genauer behandelt?', options: ['Christentum, Islam und Judentum', 'Buddhismus, Hinduismus und Islam', 'Christentum, Hinduismus und Buddhismus'], answer: 0, explanation: 'Die erste Prüfung vertieft Christentum, Islam und Judentum.' },
  { id: 'g10', topic: 'Grundwissen', prompt: 'Was haben Christentum, Islam und Judentum gemeinsam?', options: ['Sie glauben an einen Gott.', 'Sie haben dieselbe heilige Schrift.', 'Sie haben dasselbe Gebetshaus.'], answer: 0, explanation: 'Alle drei sind monotheistisch, unterscheiden sich aber unter anderem bei Schriften und Gebäuden.' },
  { id: 'g11', topic: 'Grundwissen', prompt: 'Welche Aussage über religiöse Symbole ist sachlich?', options: ['Symbole helfen bei der Zuordnung, bilden eine Religion aber nie vollständig ab.', 'Jede Religion hat weltweit genau ein verbindliches Symbol.', 'Ein Symbol erklärt alle Glaubensinhalte.'], answer: 0, explanation: 'Symbole sind Merkhilfen. Religionen und ihre Traditionen sind vielfältiger.' },
  { id: 'g12', topic: 'Grundwissen', prompt: 'Welche Zuordnung ist richtig?', options: ['Christentum–Kreuz, Judentum–Davidstern, Buddhismus–Dharma-Rad', 'Christentum–Om, Judentum–Kreuz, Buddhismus–Halbmond', 'Christentum–Davidstern, Judentum–Dharma-Rad, Buddhismus–Kreuz'], answer: 0, explanation: 'Diese drei Zeichen werden im Lernheft so zugeordnet.' },
  { id: 'g13', topic: 'Grundwissen', prompt: 'Was ist eine respektvolle Formulierung bei Glaubensaussagen?', options: ['„Christinnen und Christen glauben, dass …“', '„Alle Menschen müssen wissen, dass …“', '„Diese Religion ist die einzig vernünftige.“'], answer: 0, explanation: 'So unterscheidest du Glaubensaussagen von allgemein überprüfbaren Tatsachen.' },
  { id: 'g14', topic: 'Grundwissen', prompt: 'Warum können Religionskarten nur einen Überblick geben?', options: ['Weil in vielen Ländern Menschen verschiedener Religionen leben.', 'Weil Religionen nie mit Orten verbunden sind.', 'Weil Karten nur eine Religion zeigen dürfen.'], answer: 0, explanation: 'Karten zeigen meist Schwerpunkte und vereinfachen die tatsächliche Vielfalt.' },
  { id: 'g15', topic: 'Grundwissen', prompt: 'Welche Religion hat keinen Schöpfergott im Zentrum ihrer Lehre?', options: ['Buddhismus', 'Judentum', 'Islam'], answer: 0, explanation: 'Im Buddhismus steht nicht der Glaube an einen Schöpfergott im Zentrum.' },

  { id: 'c1', topic: 'Christentum', prompt: 'Was ist das wichtigste Zeichen des Christentums?', options: ['Das Kreuz', 'Der Davidstern', 'Das Dharma-Rad'], answer: 0, explanation: 'Das Kreuz erinnert an Jesus Christus.' },
  { id: 'c2', topic: 'Christentum', prompt: 'Wie heisst die heilige Schrift der Christinnen und Christen?', options: ['Bibel', 'Koran', 'Tora'], answer: 0, explanation: 'Die Bibel besteht aus Altem und Neuem Testament.' },
  { id: 'c3', topic: 'Christentum', prompt: 'Welche drei grossen Konfessionen solltest du kennen?', options: ['katholisch, reformiert/evangelisch, orthodox', 'sunnitisch, schiitisch, orthodox', 'katholisch, hinduistisch, buddhistisch'], answer: 0, explanation: 'Das Christentum hat verschiedene Konfessionen mit gemeinsamen Grundlagen.' },
  { id: 'c4', topic: 'Christentum', prompt: 'Was bedeutet die christliche Dreifaltigkeit?', options: ['Vater, Sohn und Heiliger Geist', 'Jesus, Mose und Mohammed', 'Bibel, Kirche und Kreuz'], answer: 0, explanation: 'Christinnen und Christen sprechen von einem Gott in Vater, Sohn und Heiligem Geist.' },
  { id: 'c5', topic: 'Christentum', prompt: 'Welche Botschaft wird Jesus im Lernheft besonders zugeordnet?', options: ['Liebe deinen Nächsten wie dich selbst.', 'Sammle möglichst viel Besitz.', 'Vermeide jede Gemeinschaft.'], answer: 0, explanation: 'Nächstenliebe ist ein Kern der Botschaft Jesu.' },
  { id: 'c6', topic: 'Christentum', prompt: 'Wo wirkte Jesus nach den Texten hauptsächlich?', options: ['Im Gebiet des heutigen Israel/Palästina', 'In Indien', 'Auf der Arabischen Halbinsel'], answer: 0, explanation: 'Jesus war Jude und lebte im Gebiet des heutigen Israel/Palästina.' },
  { id: 'c7', topic: 'Christentum', prompt: 'Was feiern Christinnen und Christen an Ostern?', options: ['Die Auferstehung Jesu', 'Die Geburt Jesu', 'Den Beginn des Ramadan'], answer: 0, explanation: 'Karfreitag erinnert an den Tod, Ostern an die Auferstehung Jesu.' },
  { id: 'c8', topic: 'Christentum', prompt: 'Was feiern Christinnen und Christen an Weihnachten?', options: ['Die Geburt Jesu', 'Die Himmelfahrt Jesu', 'Die Übergabe der Tora'], answer: 0, explanation: 'Weihnachten erinnert an die Geburt Jesu.' },
  { id: 'c9', topic: 'Christentum', prompt: 'Wie starb Jesus nach den Berichten des Neuen Testaments?', options: ['Er wurde in Jerusalem gekreuzigt.', 'Er starb als alter König.', 'Er fiel in einer Schlacht in Rom.'], answer: 0, explanation: 'Jesus wurde unter römischer Herrschaft gekreuzigt.' },
  { id: 'c10', topic: 'Christentum', prompt: 'Welche Regel passt zum Christentum?', options: ['Nächstenliebe und die Zehn Gebote', 'Die fünf Säulen', 'Der achtfache Pfad'], answer: 0, explanation: 'Nächstenliebe und die Zehn Gebote sind wichtige christliche Orientierungen.' },
  { id: 'c11', topic: 'Christentum', prompt: 'Aus welchen zwei Hauptteilen besteht die Bibel?', options: ['Altes Testament und Neues Testament', 'Tora und Koran', 'Evangelium und Ramadan'], answer: 0, explanation: 'Die christliche Bibel gliedert sich in das Alte und das Neue Testament.' },
  { id: 'c12', topic: 'Christentum', prompt: 'Wie heisst das christliche Gebetshaus?', options: ['Kirche', 'Moschee', 'Synagoge'], answer: 0, explanation: 'Christliche Gottesdienste finden meist in einer Kirche statt.' },
  { id: 'c13', topic: 'Christentum', prompt: 'Welcher Tag erinnert besonders an die Kreuzigung Jesu?', options: ['Karfreitag', 'Ostermontag', 'Heiligabend'], answer: 0, explanation: 'Karfreitag erinnert an Tod und Kreuzigung Jesu.' },
  { id: 'c14', topic: 'Christentum', prompt: 'Was war Jesus während seines öffentlichen Wirkens?', options: ['Wanderprediger', 'Römischer Kaiser', 'Händler in Mekka'], answer: 0, explanation: 'Jesus zog umher, lehrte und sprach von Gottes Liebe und Nächstenliebe.' },
  { id: 'c15', topic: 'Christentum', prompt: 'Welche Aussage beschreibt Jesus sachlich und respektvoll?', options: ['Jesus war Jude; Christinnen und Christen glauben, dass er Gottes Sohn ist.', 'Jesus gründete in Rom ein Königreich.', 'Jesus schrieb den Koran.'], answer: 0, explanation: 'Die Formulierung verbindet historisches Wissen mit der christlichen Glaubensaussage.' },

  { id: 'i1', topic: 'Islam', prompt: 'Was bedeutet das arabische Wort „Allah“?', options: ['Gott', 'Prophet', 'Gebetshaus'], answer: 0, explanation: 'Allah ist das arabische Wort für Gott; auch arabische Christinnen und Christen verwenden es.' },
  { id: 'i2', topic: 'Islam', prompt: 'Wie heisst die heilige Schrift des Islams?', options: ['Koran', 'Bibel', 'Tora'], answer: 0, explanation: 'Im Islam gilt der Koran als Offenbarung Gottes an Mohammed.' },
  { id: 'i3', topic: 'Islam', prompt: 'Wo wurde Mohammed ungefähr im Jahr 570 geboren?', options: ['Mekka', 'Medina', 'Jerusalem'], answer: 0, explanation: 'Mohammed wurde nach islamischer Überlieferung in Mekka auf der Arabischen Halbinsel geboren.' },
  { id: 'i4', topic: 'Islam', prompt: 'Welcher Engel überbrachte Mohammed nach islamischer Überlieferung Offenbarungen?', options: ['Gabriel', 'Michael', 'Raphael'], answer: 0, explanation: 'Die Überlieferung nennt den Engel Gabriel.' },
  { id: 'i5', topic: 'Islam', prompt: 'Wo empfing Mohammed die erste Offenbarung?', options: ['In der Höhle Hira bei Mekka', 'In einer Höhle bei Medina', 'In einem Tempel in Jerusalem'], answer: 0, explanation: 'Hira liegt bei Mekka. Die Formulierung „bei Medina“ in einer Aufgabe ist sehr wahrscheinlich ein Druckfehler.' },
  { id: 'i6', topic: 'Islam', prompt: 'In welche Stadt wanderte Mohammed aus?', options: ['Medina', 'Rom', 'Nazareth'], answer: 0, explanation: 'Die Auswanderung von Mekka nach Medina heisst Hidschra.' },
  { id: 'i7', topic: 'Islam', prompt: 'Wie nennen Musliminnen und Muslime Mohammed?', options: ['Prophet und Gesandter Gottes', 'Sohn Gottes', 'Gott des Mondes'], answer: 0, explanation: 'Im Islam ist Mohammed ein Mensch, Prophet und Gesandter Gottes.' },
  { id: 'i8', topic: 'Islam', prompt: 'Welche Reihe nennt die fünf Säulen des Islams?', options: ['Glaubensbekenntnis, Gebet, Almosen, Fasten, Pilgerfahrt', 'Taufe, Abendmahl, Beichte, Firmung, Ehe', 'Geburt, Schule, Beruf, Reise, Tod'], answer: 0, explanation: 'Die fünf Säulen strukturieren wichtige religiöse Pflichten.' },
  { id: 'i9', topic: 'Islam', prompt: 'Wie heisst das muslimische Gebetshaus?', options: ['Moschee', 'Kirche', 'Synagoge'], answer: 0, explanation: 'Musliminnen und Muslime versammeln sich zum Gebet in einer Moschee.' },
  { id: 'i10', topic: 'Islam', prompt: 'Was ist der Ramadan?', options: ['Ein Fastenmonat', 'Ein christliches Weihnachtsfest', 'Der jüdische Ruhetag'], answer: 0, explanation: 'Im Ramadan fasten viele Musliminnen und Muslime tagsüber.' },
  { id: 'i11', topic: 'Islam', prompt: 'Was bedeutet Hidschra?', options: ['Mohammeds Auswanderung von Mekka nach Medina', 'Die Pilgerfahrt nach Jerusalem', 'Die erste Übersetzung des Korans'], answer: 0, explanation: 'Die Hidschra fand 622 statt und ist Ausgangspunkt der islamischen Zeitrechnung.' },
  { id: 'i12', topic: 'Islam', prompt: 'Welche Säule des Islams führt nach Mekka?', options: ['Die Pilgerfahrt', 'Das Almosengeben', 'Das Fasten'], answer: 0, explanation: 'Die Pilgerfahrt nach Mekka heisst Hadsch.' },
  { id: 'i13', topic: 'Islam', prompt: 'Welche Aussage über Mohammed ist richtig?', options: ['Er war zuerst Händler und gilt im Islam als Prophet.', 'Er war ein christlicher Kaiser.', 'Er schrieb die Tora in Jerusalem.'], answer: 0, explanation: 'Mohammed arbeitete als Händler; Musliminnen und Muslime sehen ihn als Propheten und Gesandten Gottes.' },
  { id: 'i14', topic: 'Islam', prompt: 'In welcher Stadt starb Mohammed im Jahr 632?', options: ['Medina', 'Mekka', 'Bethlehem'], answer: 0, explanation: 'Mohammed starb nach der Überlieferung 632 in Medina.' },
  { id: 'i15', topic: 'Islam', prompt: 'Welche Formulierung unterscheidet Glaube und Geschichte?', options: ['„Nach islamischer Überlieferung erhielt Mohammed Offenbarungen durch Gabriel.“', '„Alle Menschen wissen, dass Gabriel erschien.“', '„Überlieferungen sind immer naturwissenschaftliche Beweise.“'], answer: 0, explanation: '„Nach islamischer Überlieferung“ kennzeichnet die Glaubensperspektive respektvoll.' },

  { id: 'j1', topic: 'Judentum', prompt: 'Welches Zeichen wird dem Judentum häufig zugeordnet?', options: ['Davidstern', 'Kreuz', 'Om'], answer: 0, explanation: 'Der sechszackige Davidstern ist ein verbreitetes jüdisches Zeichen.' },
  { id: 'j2', topic: 'Judentum', prompt: 'Wie heisst das jüdische Gebetshaus?', options: ['Synagoge', 'Moschee', 'Kirche'], answer: 0, explanation: 'In der Synagoge wird gebetet, gelernt und Gemeinschaft gelebt.' },
  { id: 'j3', topic: 'Judentum', prompt: 'Was ist die Tora?', options: ['Die fünf Bücher Mose und Kern der jüdischen heiligen Schriften', 'Ein christliches Fest', 'Ein muslimisches Gebet'], answer: 0, explanation: 'Die Tora wird auf Schriftrollen geschrieben und in der Synagoge gelesen.' },
  { id: 'j4', topic: 'Judentum', prompt: 'Welche Aussage ist richtig?', options: ['Das Judentum ist monotheistisch.', 'Das Judentum verehrt viele Gottheiten.', 'Jüdinnen und Juden haben keine heiligen Schriften.'], answer: 0, explanation: 'Im Judentum steht der Glaube an den einen Gott im Zentrum.' },
  { id: 'j5', topic: 'Judentum', prompt: 'Welcher Tag ist der jüdische Ruhetag?', options: ['Schabbat', 'Freitag der Kreuzigung', 'Ramadan'], answer: 0, explanation: 'Der Schabbat beginnt am Freitagabend und endet am Samstagabend.' },
  { id: 'j6', topic: 'Judentum', prompt: 'Welche Regel gehört zum Judentum?', options: ['Zehn Gebote und Speiseregeln (koscher)', 'Fünf Säulen', 'Achtfacher Pfad'], answer: 0, explanation: 'Zu jüdischen Traditionen gehören Gebote, Schabbat und unterschiedliche Formen koscherer Ernährung.' },
  { id: 'j7', topic: 'Judentum', prompt: 'Wann beginnt der Schabbat?', options: ['Am Freitagabend', 'Am Sonntagmittag', 'Am Montagmorgen'], answer: 0, explanation: 'Der Schabbat beginnt am Freitagabend und dauert bis Samstagabend.' },
  { id: 'j8', topic: 'Judentum', prompt: 'Wie wird die Tora in vielen Synagogen aufbewahrt?', options: ['Als Schriftrollen im Toraschrein', 'Als Steintafel im Kirchturm', 'Als Buch im Minarett'], answer: 0, explanation: 'Torarollen werden im Toraschrein aufbewahrt.' },
  { id: 'j9', topic: 'Judentum', prompt: 'Welche wichtige Person verbindet man im Lernstoff besonders mit der Tora?', options: ['Mose', 'Mohammed', 'Buddha'], answer: 0, explanation: 'Die Tora umfasst die fünf Bücher Mose; Mose ist eine zentrale Gestalt der jüdischen Tradition.' },
  { id: 'j10', topic: 'Judentum', prompt: 'Was bedeutet „koscher“ im Zusammenhang mit Essen?', options: ['Nach jüdischen Speiseregeln erlaubt oder geeignet', 'Während des Ramadan gegessen', 'Nur an Weihnachten gekocht'], answer: 0, explanation: 'Koscher bezeichnet unter anderem Lebensmittel, die jüdischen Speiseregeln entsprechen.' },
  { id: 'j11', topic: 'Judentum', prompt: 'Was geschieht an der Bima in einer Synagoge?', options: ['Aus der Tora wird gelesen.', 'Die Gebetsrichtung nach Mekka wird angezeigt.', 'Hostien werden aufbewahrt.'], answer: 0, explanation: 'Die Bima ist das Lesepult beziehungsweise der erhöhte Ort für die Toralesung.' },
  { id: 'j12', topic: 'Judentum', prompt: 'Welche Aussage zu Judentum und Christentum stimmt?', options: ['Beide kennen die Zehn Gebote.', 'Beide verwenden den Koran als heilige Schrift.', 'Beide feiern den Ramadan.'], answer: 0, explanation: 'Die Zehn Gebote spielen in Judentum und Christentum eine wichtige Rolle.' },
  { id: 'j13', topic: 'Judentum', prompt: 'Was gehört zum Leben in einer Synagoge?', options: ['Beten, Lernen und Gemeinschaft', 'Nur Sport und Handel', 'Ausschliesslich stilles Lesen ohne Gottesdienst'], answer: 0, explanation: 'Eine Synagoge ist Gebets-, Lern- und Versammlungsort.' },
  { id: 'j14', topic: 'Judentum', prompt: 'Was bedeutet Tanach?', options: ['Bezeichnung für die jüdische Bibel', 'Name einer Moschee', 'Christliches Abendmahl'], answer: 0, explanation: 'Der Tanach ist die Sammlung der heiligen Schriften des Judentums; die Tora ist ein zentraler Teil davon.' },
  { id: 'j15', topic: 'Judentum', prompt: 'Welche Kombination gehört zum Judentum?', options: ['Davidstern – Synagoge – Tora', 'Kreuz – Moschee – Bibel', 'Halbmond – Kirche – Koran'], answer: 0, explanation: 'Davidstern, Synagoge und Tora sind die gesuchte Zuordnung.' },

  { id: 'b1', topic: 'Gebäude & Schriften', prompt: 'Wo befindet sich der Altar?', options: ['In einer Kirche', 'Nur in einer Moschee', 'Nur in einer Synagoge'], answer: 0, explanation: 'In katholischen Kirchen ist der Altar ein zentraler Ort der Eucharistiefeier.' },
  { id: 'b2', topic: 'Gebäude & Schriften', prompt: 'Was ist ein Tabernakel?', options: ['Ein Aufbewahrungsort für geweihte Hostien in einer katholischen Kirche', 'Der Gebetsteppich in einer Moschee', 'Der Toraschrein'], answer: 0, explanation: 'Der Tabernakel befindet sich meist nahe beim Altar und ist häufig durch ein Licht gekennzeichnet.' },
  { id: 'b3', topic: 'Gebäude & Schriften', prompt: 'Was zeigt die Gebetsrichtung in einer Moschee an?', options: ['Die Gebetsnische Mihrab', 'Der Kirchturm', 'Die Orgel'], answer: 0, explanation: 'Der Mihrab zeigt die Gebetsrichtung nach Mekka (Qibla) an.' },
  { id: 'b4', topic: 'Gebäude & Schriften', prompt: 'Was ist ein Minbar?', options: ['Eine Kanzel in der Moschee', 'Ein Taufbecken', 'Ein Toraschrein'], answer: 0, explanation: 'Vom Minbar aus wird besonders beim Freitagsgebet gepredigt.' },
  { id: 'b5', topic: 'Gebäude & Schriften', prompt: 'Wo werden Torarollen aufbewahrt?', options: ['Im Toraschrein der Synagoge', 'Im Minarett', 'Im Taufbecken'], answer: 0, explanation: 'Der Toraschrein ist ein besonders wichtiger Ort in der Synagoge.' },
  { id: 'b6', topic: 'Gebäude & Schriften', prompt: 'Welche Zuordnung ist vollständig richtig?', options: ['Kirche–Bibel, Moschee–Koran, Synagoge–Tora', 'Kirche–Koran, Moschee–Tora, Synagoge–Bibel', 'Kirche–Tora, Moschee–Bibel, Synagoge–Koran'], answer: 0, explanation: 'Diese drei Paare gehören zum Kernwissen für Prüfung Teil 1.' },
  { id: 'b7', topic: 'Gebäude & Schriften', prompt: 'Was ist ein Ambo?', options: ['Das Lesepult in einer Kirche', 'Eine Gebetsnische in einer Moschee', 'Der Schrein für Torarollen'], answer: 0, explanation: 'Vom Ambo werden in der Kirche biblische Texte und Fürbitten vorgetragen.' },
  { id: 'b8', topic: 'Gebäude & Schriften', prompt: 'Wozu dient ein Taufbecken?', options: ['Zur christlichen Taufe', 'Zur Aufbewahrung des Korans', 'Zur Toralesung'], answer: 0, explanation: 'Am Taufbecken wird die Taufe mit Wasser gefeiert.' },
  { id: 'b9', topic: 'Gebäude & Schriften', prompt: 'Was bedeutet Qibla?', options: ['Gebetsrichtung nach Mekka', 'Name der Kanzel', 'Waschraum der Kirche'], answer: 0, explanation: 'Qibla nennt man die Richtung nach Mekka, in die Musliminnen und Muslime beten.' },
  { id: 'b10', topic: 'Gebäude & Schriften', prompt: 'Wozu dient der Ort der Waschung in einer Moschee?', options: ['Zur rituellen Reinigung vor dem Gebet', 'Zur Taufe', 'Zum Aufbewahren der Tora'], answer: 0, explanation: 'Vor dem Gebet führen viele Musliminnen und Muslime eine rituelle Waschung durch.' },
  { id: 'b11', topic: 'Gebäude & Schriften', prompt: 'Was ist das Ewige Licht in einer Synagoge?', options: ['Ein Licht in der Nähe des Toraschreins', 'Ein Fenster im Minarett', 'Die Kerze auf dem Taufbecken'], answer: 0, explanation: 'Das Ewige Licht befindet sich in vielen Synagogen über oder nahe dem Toraschrein.' },
  { id: 'b12', topic: 'Gebäude & Schriften', prompt: 'Welches Möbelstück gehört zur Synagoge?', options: ['Bima', 'Minbar', 'Tabernakel'], answer: 0, explanation: 'Die Bima ist der Ort beziehungsweise das Lesepult für die Toralesung.' },
  { id: 'b13', topic: 'Gebäude & Schriften', prompt: 'Welche Kombination gehört zur Moschee?', options: ['Mihrab – Minbar – Gebetsteppiche', 'Altar – Tabernakel – Taufbecken', 'Toraschrein – Bima – Ewiges Licht'], answer: 0, explanation: 'Mihrab, Minbar und Gebetsteppiche sind typische Elemente einer Moschee.' },
  { id: 'b14', topic: 'Gebäude & Schriften', prompt: 'Welche Kombination gehört zur katholischen Kirche?', options: ['Altar – Ambo – Tabernakel', 'Mihrab – Minbar – Qibla', 'Bima – Toraschrein – Torarollen'], answer: 0, explanation: 'Altar, Ambo und Tabernakel sind wichtige Orte in einer katholischen Kirche.' },
  { id: 'b15', topic: 'Gebäude & Schriften', prompt: 'Welche Kombination gehört zur Synagoge?', options: ['Toraschrein – Bima – Ewiges Licht', 'Altar – Orgel – Tabernakel', 'Mihrab – Minbar – Waschungsort'], answer: 0, explanation: 'Toraschrein, Bima und Ewiges Licht sind typische Elemente einer Synagoge.' },
  { id: 'g16', topic: 'Grundwissen', prompt: 'Welche drei Gebetshäuser gehören zu den drei monotheistischen Prüfungsreligionen?', options: ['Kirche, Moschee und Synagoge', 'Tempel, Pagode und Schrein', 'Kloster, Stadion und Rathaus'], answer: 0, explanation: 'Kirche, Moschee und Synagoge gehören zu Christentum, Islam und Judentum.' },
  { id: 'g17', topic: 'Grundwissen', prompt: 'Was ist ein religiöses Ritual?', options: ['Eine wiederkehrende Handlung mit religiöser Bedeutung', 'Eine zufällige Freizeitbeschäftigung', 'Eine Landkarte der Welt'], answer: 0, explanation: 'Gebete, Gottesdienste oder Feste können Rituale enthalten.' },
  { id: 'g18', topic: 'Grundwissen', prompt: 'Welcher Wortteil bedeutet „eins“?', options: ['mono', 'poly', 'theos'], answer: 0, explanation: '„mono“ bedeutet eins; deshalb bezeichnet Monotheismus den Glauben an einen Gott.' },
  { id: 'g19', topic: 'Grundwissen', prompt: 'Welche Aussage passt am besten zum Hinduismus im Überblick?', options: ['Es gibt vielfältige Gottesvorstellungen.', 'Es gibt nur eine weltweit einheitliche Glaubensform.', 'Das Kreuz ist sein wichtigstes Zeichen.'], answer: 0, explanation: 'Hinduistische Traditionen sind vielfältig und kennen unterschiedliche Vorstellungen vom Göttlichen.' },
  { id: 'g20', topic: 'Grundwissen', prompt: 'Was ist beim Vergleichen von Religionen wichtig?', options: ['Gemeinsamkeiten und Unterschiede sachlich und respektvoll benennen', 'Eine Religion als besser bewerten', 'Alle Unterschiede verschweigen'], answer: 0, explanation: 'Ein guter Vergleich ist genau, respektvoll und vermeidet Bewertungen.' },
  { id: 'c16', topic: 'Christentum', prompt: 'In welchem Teil der Bibel stehen die Evangelien über Jesus?', options: ['Im Neuen Testament', 'Im Koran', 'In den Veden'], answer: 0, explanation: 'Die vier Evangelien gehören zum Neuen Testament.' },
  { id: 'c17', topic: 'Christentum', prompt: 'Welches Zeichen wird bei der christlichen Taufe verwendet?', options: ['Wasser', 'Gebetsteppich', 'Torarolle'], answer: 0, explanation: 'Die Taufe wird mit Wasser gefeiert und gehört zu wichtigen christlichen Ritualen.' },
  { id: 'c18', topic: 'Christentum', prompt: 'Woran erinnert ein Kruzifix?', options: ['An Jesus am Kreuz', 'An Mohammeds Reise nach Medina', 'An die Toralesung'], answer: 0, explanation: 'Ein Kruzifix ist ein Kreuz mit der Darstellung des gekreuzigten Jesus.' },
  { id: 'c19', topic: 'Christentum', prompt: 'Was bedeutet „Nächstenliebe“?', options: ['Anderen Menschen mit Liebe und Hilfe begegnen', 'Nur an sich selbst denken', 'Religiöse Gebäude vergleichen'], answer: 0, explanation: 'Nächstenliebe bedeutet, Mitmenschen zu achten und ihnen beizustehen.' },
  { id: 'c20', topic: 'Christentum', prompt: 'Welche Reihenfolge passt zur Osterzeit?', options: ['Karfreitag – Tod Jesu; Ostern – Auferstehung', 'Ostern – Geburt Jesu; Karfreitag – Taufe', 'Karfreitag – Ramadan; Ostern – Schabbat'], answer: 0, explanation: 'Karfreitag erinnert an Jesu Tod, Ostern an seine Auferstehung.' },
  { id: 'i16', topic: 'Islam', prompt: 'Wie oft am Tag gehört das Gebet traditionell zu den fünf Säulen?', options: ['Fünfmal', 'Einmal pro Woche', 'Nur einmal im Leben'], answer: 0, explanation: 'Das rituelle Gebet wird traditionell fünfmal täglich verrichtet.' },
  { id: 'i17', topic: 'Islam', prompt: 'Was bedeutet die Säule des Almosengebens?', options: ['Bedürftige unterstützen und Besitz teilen', 'Nach Mekka auswandern', 'Eine Kirche bauen'], answer: 0, explanation: 'Das verpflichtende Almosen wird Zakat genannt und unterstützt Menschen in Not.' },
  { id: 'i18', topic: 'Islam', prompt: 'Was ist das Glaubensbekenntnis im Islam?', options: ['Das Bekenntnis zu dem einen Gott und zu Mohammed als seinem Gesandten', 'Ein christliches Osterlied', 'Eine jüdische Speiseregel'], answer: 0, explanation: 'Das Glaubensbekenntnis ist die erste der fünf Säulen.' },
  { id: 'i19', topic: 'Islam', prompt: 'Wann fasten viele Musliminnen und Muslime im Ramadan?', options: ['Von der Morgendämmerung bis zum Sonnenuntergang', 'Nur jeden Sonntagmorgen', 'Während des ganzen Jahres ohne Unterbruch'], answer: 0, explanation: 'Im Ramadan wird tagsüber gefastet; für bestimmte Menschen gelten Ausnahmen.' },
  { id: 'i20', topic: 'Islam', prompt: 'Welche Stadt ist die Gebetsrichtung muslimischer Gebete?', options: ['Mekka', 'Rom', 'Nazareth'], answer: 0, explanation: 'Die Qibla weist in Richtung der Kaaba in Mekka.' },
  { id: 'j16', topic: 'Judentum', prompt: 'Welche Gebote verbinden Judentum und Christentum?', options: ['Die Zehn Gebote', 'Die fünf Säulen', 'Die vier Evangelien'], answer: 0, explanation: 'Die Zehn Gebote sind für jüdische und christliche Traditionen wichtig.' },
  { id: 'j17', topic: 'Judentum', prompt: 'Warum werden Torarollen besonders sorgfältig behandelt?', options: ['Weil die Tora eine heilige Schrift ist', 'Weil sie eine Landkarte enthält', 'Weil sie zum Minbar gehört'], answer: 0, explanation: 'Torarollen enthalten den heiligen Text und werden mit grossem Respekt behandelt.' },
  { id: 'j18', topic: 'Judentum', prompt: 'Welche Person gilt in Judentum, Christentum und Islam als wichtig?', options: ['Abraham', 'Buddha', 'Der römische Kaiser Nero'], answer: 0, explanation: 'Abraham ist eine bedeutende Gestalt in allen drei monotheistischen Religionen.' },
  { id: 'j19', topic: 'Judentum', prompt: 'Wofür ist der Schabbat besonders bestimmt?', options: ['Ruhe, Gebet, Familie und Gemeinschaft', 'Pilgerfahrt nach Mekka', 'Erinnerung an die Kreuzigung'], answer: 0, explanation: 'Der Schabbat ist ein wöchentlicher Ruhetag mit religiöser und familiärer Bedeutung.' },
  { id: 'j20', topic: 'Judentum', prompt: 'Welche Aussage zur Tora ist falsch?', options: ['Sie ist die heilige Schrift des Islams.', 'Sie umfasst die fünf Bücher Mose.', 'Sie wird in der Synagoge gelesen.'], answer: 0, explanation: 'Die heilige Schrift des Islams ist der Koran; die anderen Aussagen zur Tora stimmen.' },
  { id: 'b16', topic: 'Gebäude & Schriften', prompt: 'In welchem Gebetshaus findet man häufig eine Orgel?', options: ['In einer Kirche', 'In jeder Moschee', 'Im Toraschrein'], answer: 0, explanation: 'Viele Kirchen besitzen eine Orgel zur Begleitung von Gesang und Gottesdienst.' },
  { id: 'b17', topic: 'Gebäude & Schriften', prompt: 'Was ist ein Minarett?', options: ['Ein Turm, der zu vielen Moscheen gehört', 'Das Lesepult einer Synagoge', 'Der Altarraum einer Kirche'], answer: 0, explanation: 'Ein Minarett ist ein Turm einer Moschee; nicht jede Moschee besitzt eines.' },
  { id: 'b18', topic: 'Gebäude & Schriften', prompt: 'Welcher Ort und welche Schrift gehören zusammen?', options: ['Toraschrein und Tora', 'Tabernakel und Koran', 'Mihrab und Bibel'], answer: 0, explanation: 'Im Toraschrein werden die Torarollen aufbewahrt.' },
  { id: 'b19', topic: 'Gebäude & Schriften', prompt: 'Du siehst Mihrab, Minbar und Gebetsteppiche. Welches Gebäude ist es?', options: ['Eine Moschee', 'Eine katholische Kirche', 'Eine Synagoge'], answer: 0, explanation: 'Diese drei Merkmale helfen, den Innenraum einer Moschee zu erkennen.' },
  { id: 'b20', topic: 'Gebäude & Schriften', prompt: 'Du siehst Toraschrein, Bima und Ewiges Licht. Welches Gebäude ist es?', options: ['Eine Synagoge', 'Eine Moschee', 'Eine Kirche'], answer: 0, explanation: 'Diese Merkmale gehören zum Innenraum einer Synagoge.' },
  { id: 'g21', topic: 'Grundwissen', prompt: 'Welche Aussage über Religion passt zum Grundtext im Arbeitsheft?', options: ['Religionen sind Weltanschauungen und gelebte Traditionen.', 'Religionen sind naturwissenschaftliche Beweise.', 'Religionen bestehen nur aus Gebäuden.'], answer: 0, explanation: 'Religionen beschäftigen sich unter anderem mit Sinnfragen, Glauben, Werten, Verhalten, Festen und Gemeinschaft.' },
  { id: 'g22', topic: 'Grundwissen', prompt: 'Was kann Religion Menschen laut Arbeitsheft geben?', options: ['Halt und Orientierung', 'Einen Beweis für jede Glaubensaussage', 'Für alle dieselbe Lebensweise'], answer: 0, explanation: 'Das Heft nennt Halt; religiöse Überzeugungen sind jedoch nicht wie naturwissenschaftliche Aussagen beweisbar.' },
  { id: 'g23', topic: 'Grundwissen', prompt: 'Welche Zuordnung aus der Weltkarte des Hefts stimmt?', options: ['Hinduismus–gelb, Islam–grün, Christentum–violett', 'Hinduismus–blau, Islam–orange, Christentum–grün', 'Hinduismus–violett, Islam–gelb, Christentum–blau'], answer: 0, explanation: 'Das sind die Farben der vereinfachten Unterrichtskarte; sie zeigen Schwerpunkte, keine scharfen Grenzen.' },
  { id: 'g24', topic: 'Grundwissen', prompt: 'Welche Freiheit nennt der Grundtext ausdrücklich?', options: ['Menschen dürfen ihre Religion frei wählen oder keiner Religion angehören.', 'Alle Menschen müssen dieselbe Religion wählen.', 'Nur Erwachsene dürfen eine Weltanschauung haben.'], answer: 0, explanation: 'Glaubens- und Gewissensfreiheit schliesst auch das Recht ein, keiner Religion anzugehören.' },
  { id: 'g25', topic: 'Grundwissen', prompt: 'Wie soll man Menschen mit einer anderen Religion behandeln?', options: ['Respektvoll und ohne Benachteiligung', 'Misstrauisch und unfair', 'Nur dann freundlich, wenn sie gleich glauben'], answer: 0, explanation: 'Das Arbeitsheft fordert Respekt und gleiche Behandlung unabhängig vom Glauben.' },
  { id: 'g26', topic: 'Grundwissen', prompt: 'Welche Aussage unterscheidet Glauben und Naturwissenschaft richtig?', options: ['Glaubensaussagen werden nicht auf dieselbe Weise bewiesen wie naturwissenschaftliche Aussagen.', 'Jede Glaubensaussage ist ein naturwissenschaftliches Experiment.', 'Naturwissenschaft und Religion stellen immer genau dieselben Fragen.'], answer: 0, explanation: 'Religionen und Naturwissenschaften können unterschiedliche Fragen, Methoden und Deutungen haben.' },
  { id: 'g27', topic: 'Grundwissen', prompt: 'Welchen Schwerpunkt zeigt die Karte des Hefts für den Buddhismus?', options: ['Ost- und Südostasien', 'Nur Südamerika', 'Nur Nordeuropa'], answer: 0, explanation: 'Die Karte färbt Teile Asiens orange; buddhistische Gemeinschaften gibt es aber auch ausserhalb dieser Region.' },
  { id: 'g28', topic: 'Grundwissen', prompt: 'Welchen Schwerpunkt zeigt die Karte des Hefts für den Hinduismus?', options: ['Indien und Südasien', 'Die Arabische Halbinsel', 'Skandinavien'], answer: 0, explanation: 'Die gelbe Markierung liegt vor allem in Indien; die tatsächliche Verbreitung ist vielfältiger.' },
  { id: 'g29', topic: 'Grundwissen', prompt: 'Welche beiden Religionen gehören in Teil 1 nur zum gemeinsamen Überblick?', options: ['Hinduismus und Buddhismus', 'Christentum und Islam', 'Islam und Judentum'], answer: 0, explanation: 'Die Detailblöcke zu Hinduismus und Buddhismus gehören laut Lernzielblatt zu Teil 2.' },
  { id: 'g30', topic: 'Grundwissen', prompt: 'Welche Zahlenfolge löst die 100er-Grafik im Heft richtig?', options: ['31 Christen, 23 Muslime, 15 Hindus, 1 Jude, 7 Buddhisten, 23 andere/keine', '31 Christen, 22 Muslime, 14 Hindus, 1 Jude, 7 Buddhisten, 25 andere/keine', '25 Christen, 31 Muslime, 23 Hindus, 7 Juden, 1 Buddhist, 13 andere/keine'], answer: 0, explanation: 'Die Felder ergeben 31+23+15+1+7+23=100. Die Grafik ist eine Zählübung und keine aktuelle Weltstatistik.' },

  { id: 'c21', topic: 'Christentum', prompt: 'Warum ist der Sonntag für Christinnen und Christen ein besonderer Tag?', options: ['Er erinnert an die Auferstehung Jesu.', 'Er erinnert an Mohammeds Auswanderung.', 'An diesem Tag beginnt der Schabbat.'], answer: 0, explanation: 'Christinnen und Christen feiern am Sonntag den Tag der Auferstehung und versammeln sich zum Gottesdienst.' },
  { id: 'c22', topic: 'Christentum', prompt: 'Wie viele grosse christliche Konfessionen nennt das Arbeitsheft?', options: ['Drei', 'Fünf', 'Sieben'], answer: 0, explanation: 'Genannt werden die römisch-katholische, die evangelische/reformierte und die orthodoxe Kirche.' },
  { id: 'c23', topic: 'Christentum', prompt: 'Wer ist das Oberhaupt der römisch-katholischen Kirche?', options: ['Der Papst', 'Der Imam', 'Der Rabbiner'], answer: 0, explanation: 'Der Papst ist Bischof von Rom und Oberhaupt der römisch-katholischen Kirche.' },
  { id: 'c24', topic: 'Christentum', prompt: 'Mit wem verbindet das Arbeitsheft den Beginn der Reformation von 1517?', options: ['Martin Luther', 'Mose', 'Siddhartha Gautama'], answer: 0, explanation: 'Das Heft nennt Martin Luther. Historisch war die Reformation eine breitere Bewegung mit mehreren Reformatoren.' },
  { id: 'c25', topic: 'Christentum', prompt: 'Wie nennt man Heiligenbilder in orthodoxen Kirchen?', options: ['Ikonen', 'Suren', 'Tefillin'], answer: 0, explanation: 'Ikonen sind religiöse Bilddarstellungen, die in orthodoxen Traditionen eine wichtige Rolle spielen.' },
  { id: 'c26', topic: 'Christentum', prompt: 'Wie heissen die leitenden Bischöfe vieler orthodoxer Kirchen?', options: ['Patriarchen', 'Muezzine', 'Kardinäle'], answer: 0, explanation: 'Viele orthodoxe Kirchen werden von Patriarchen oder anderen leitenden Bischöfen geführt.' },
  { id: 'c27', topic: 'Christentum', prompt: 'Was geschah laut Bibel 40 Tage nach der Auferstehung Jesu?', options: ['Jesus verliess die Jünger; daran erinnert Christi Himmelfahrt.', 'Jesus wurde in Bethlehem geboren.', 'Jesus begann als Wanderprediger.'], answer: 0, explanation: 'Das Arbeitsblatt verbindet die 40 Tage nach Ostern mit Christi Himmelfahrt.' },
  { id: 'c28', topic: 'Christentum', prompt: 'Welche Gemeinschaft ist ein Beispiel für eine Freikirche?', options: ['Die Baptisten', 'Die römisch-katholische Kirche', 'Eine orthodoxe Landeskirche'], answer: 0, explanation: 'Baptistische Gemeinden zählen zu den Freikirchen; daneben gibt es weitere freikirchliche Gemeinschaften.' },
  { id: 'c29', topic: 'Christentum', prompt: 'Was erhoffen sich viele Christinnen und Christen von einer Pilgerreise?', options: ['Den Glauben zu vertiefen und sich auf Gott zu besinnen', 'Eine neue heilige Schrift zu verfassen', 'Den Sonntag durch den Freitag zu ersetzen'], answer: 0, explanation: 'Eine Pilgerreise kann Gebet, Besinnung, Gemeinschaft und eine Vertiefung des Glaubens ermöglichen.' },
  { id: 'c30', topic: 'Christentum', prompt: 'Welche Aussage zur evangelischen Kirche nennt das Arbeitsheft?', options: ['Pfarrerinnen und Pfarrer dürfen heiraten.', 'Sie hat den Papst als Oberhaupt.', 'Sie entstand aus der orthodoxen Kirche im Jahr 1054.'], answer: 0, explanation: 'Das Heft nennt verheiratete Pfarrpersonen und Frauen im Pfarramt als Merkmale evangelischer Kirchen.' },

  { id: 'i21', topic: 'Islam', prompt: 'Was bedeutet „Moschee“ im Arbeitsheft?', options: ['Haus des Gebets', 'Haus der Taufe', 'Haus der Torarollen'], answer: 0, explanation: 'In der Moschee kommen Musliminnen und Muslime zum gemeinsamen Gebet zusammen.' },
  { id: 'i22', topic: 'Islam', prompt: 'Wie nennt man den Gebetsrufer einer Moschee?', options: ['Muezzin', 'Patriarch', 'Rabbiner'], answer: 0, explanation: 'Der Muezzin ruft zum Gebet; der Imam leitet das Gebet und kann predigen.' },
  { id: 'i23', topic: 'Islam', prompt: 'Warum gibt es vor dem Gebetsraum oft ein Schuhregal?', options: ['Weil man den Gebetsraum ohne Schuhe betritt.', 'Weil Schuhe eine der fünf Säulen sind.', 'Weil dort der Koran aufbewahrt wird.'], answer: 0, explanation: 'Vor dem Betreten des Gebetsraums werden die Schuhe ausgezogen.' },
  { id: 'i24', topic: 'Islam', prompt: 'Was findet man an vielen Moscheewänden statt bildlicher Darstellungen?', options: ['Kalligrafisch geschriebene Koranverse', 'Ikonen von Heiligen', 'Bilder der Dreifaltigkeit'], answer: 0, explanation: 'Das Arbeitsblatt nennt arabische Koranverse und Kalligrafie als typische Gestaltung.' },
  { id: 'i25', topic: 'Islam', prompt: 'Wie werden Koranverse im Gottesdienst vorgetragen?', options: ['Sie werden rezitiert.', 'Sie werden als Oper gesungen.', 'Sie werden nur still gelesen.'], answer: 0, explanation: 'Der passende Fachausdruck ist „rezitieren“. Der Vortrag kann melodisch klingen, gilt aber nicht einfach als Gesang.' },
  { id: 'i26', topic: 'Islam', prompt: 'Was beschreiben die 99 Namen Allahs?', options: ['Eigenschaften Gottes', 'Die Namen von 99 Propheten', 'Die Teile einer Moschee'], answer: 0, explanation: 'Beispiele sind der Barmherzige, der Weise, der Liebende oder der Beschützer.' },
  { id: 'i27', topic: 'Islam', prompt: 'Welche Formulierung gibt alle fünf Säulen vollständig wieder?', options: ['Glaubensbekenntnis, fünf tägliche Gebete, Zakat, Ramadanfasten, Hadsch', 'Glaubensbekenntnis, Taufe, Schabbat, Ikonen, Pilgerfahrt', 'Gebet, Tora, Ostern, Altar, Fasten'], answer: 0, explanation: 'In einer Antwort von David fehlte das tägliche Gebet; alle fünf Bestandteile müssen genannt werden.' },
  { id: 'i28', topic: 'Islam', prompt: 'Welcher Gottesname passt zur Formulierung des Arbeitsblatts?', options: ['Der Liebende', 'Der Geliebte', 'Der Unbekannte'], answer: 0, explanation: '„Der Liebende“ beschreibt Gott als den, der liebt. „Der Geliebte“ bedeutet etwas anderes.' },
  { id: 'i29', topic: 'Islam', prompt: 'Was ist ein Imam?', options: ['Ein Vorbeter und religiöser Leiter', 'Der Gebetsrufer auf dem Minarett', 'Ein christlicher Bischof'], answer: 0, explanation: 'Der Imam leitet das gemeinschaftliche Gebet und hält häufig die Freitagspredigt.' },
  { id: 'i30', topic: 'Islam', prompt: 'Welche Aussage über die Höhle Hira ist richtig?', options: ['Sie liegt bei Mekka.', 'Sie liegt bei Medina.', 'Sie liegt in Jerusalem.'], answer: 0, explanation: 'Hira liegt bei Mekka. Die Formulierung „bei Medina“ auf einem Aufgabenblatt ist ein Fehler.' },

  { id: 'j21', topic: 'Judentum', prompt: 'Wie heisst der heilige Ruhetag im Judentum korrekt?', options: ['Schabbat oder Sabbat', 'Sonntag', 'Ramadan'], answer: 0, explanation: 'Der Schabbat dauert von Freitagabend bis Samstagabend. „Sabat“ ist in der deutschen Antwort falsch geschrieben.' },
  { id: 'j22', topic: 'Judentum', prompt: 'Was ist eine Kippa?', options: ['Eine jüdische Kopfbedeckung', 'Ein Gebetsschal', 'Ein Gebetskästchen am Arm'], answer: 0, explanation: 'Die Kippa ist eine kleine Kopfbedeckung, die viele jüdische Männer und Jungen tragen.' },
  { id: 'j23', topic: 'Judentum', prompt: 'Was ist ein Tallit?', options: ['Ein jüdischer Gebetsschal', 'Der Schrein für die Tora', 'Ein siebenarmiger Leuchter'], answer: 0, explanation: 'Der Tallit ist ein Gebetsschal mit Schaufäden.' },
  { id: 'j24', topic: 'Judentum', prompt: 'Was sind Tefillin?', options: ['Gebetsriemen mit kleinen Kapseln und Toratexten', 'Kerzen für Weihnachten', 'Schuhe für die Synagoge'], answer: 0, explanation: 'Tefillin werden beim Gebet an Arm und Kopf getragen; die Kapseln enthalten Schriftstellen.' },
  { id: 'j25', topic: 'Judentum', prompt: 'Welche Lebensmittel werden nach traditionellen jüdischen Speiseregeln nicht zusammen gegessen?', options: ['Fleisch und Milchprodukte', 'Brot und Wasser', 'Obst und Gemüse'], answer: 0, explanation: 'Die traditionelle Kaschrut trennt Fleischiges und Milchiges.' },
  { id: 'j26', topic: 'Judentum', prompt: 'Wie heisst die Hülse am Türpfosten, die einen Pergamenttext enthält?', options: ['Mesusa', 'Menora', 'Bima'], answer: 0, explanation: 'Die Mesusa wird am Türpfosten befestigt und enthält ein Pergament mit Toraversen.' },
  { id: 'j27', topic: 'Judentum', prompt: 'Wie nennt man die heilige Stätte in Jerusalem, an der viele Menschen beten?', options: ['Westmauer oder Klagemauer', 'Minbar', 'Vatikan'], answer: 0, explanation: 'Die Westmauer ist ein erhaltener Teil der Stützmauer des früheren Tempelbergs und ein bedeutender jüdischer Gebetsort.' },
  { id: 'j28', topic: 'Judentum', prompt: 'Was ist ein Rabbiner?', options: ['Ein Lehrer und Ausleger der jüdischen Tradition', 'Ein jüdischer Priester', 'Der Gebetsrufer einer Moschee'], answer: 0, explanation: 'Rabbiner sind religiöse Lehrer und Gelehrte; sie sind nicht einfach Priester.' },
  { id: 'j29', topic: 'Judentum', prompt: 'Welche Antwort passt im Lernpaket am besten zur Frage nach dem Symbol des Judentums?', options: ['Davidstern', 'Menora als einzige mögliche Antwort', 'Kreuz'], answer: 0, explanation: 'Die Menora ist ebenfalls ein wichtiges jüdisches Symbol. Im Lernpaket wird zur eindeutigen Zuordnung jedoch der Davidstern verwendet.' },
  { id: 'j30', topic: 'Judentum', prompt: 'Welche aktuelle Einordnung der Zahl jüdischer Menschen ist sachlich?', options: ['Die Zahl hängt von Definition und Jahr ab; 14 Millionen ist eine ältere Rundung.', 'Weltweit gibt es genau 14 Millionen, unverändert für immer.', 'Die Zahl lässt sich überhaupt nicht schätzen.'], answer: 0, explanation: 'Für die Karteikarte kann die ältere Zahl verlangt sein; aktuelle Schätzungen liegen höher und verwenden klar definierte Bevölkerungsbegriffe.' },

  { id: 'b21', topic: 'Gebäude & Schriften', prompt: 'Du siehst ein Schuhregal, einen Waschungsort und eine Gebetsnische. Wo bist du?', options: ['In einer Moschee', 'In einer Kirche', 'In einer Synagoge'], answer: 0, explanation: 'Schuhe ausziehen, rituelle Waschung und Mihrab sind typische Hinweise auf eine Moschee.' },
  { id: 'b22', topic: 'Gebäude & Schriften', prompt: 'Welche Person und welcher Gebäudeteil gehören zusammen?', options: ['Imam–Minbar', 'Papst–Bima', 'Rabbiner–Mihrab'], answer: 0, explanation: 'Der Imam kann die Freitagspredigt vom Minbar aus halten.' },
  { id: 'b23', topic: 'Gebäude & Schriften', prompt: 'Welche drei Dinge sind jüdische Zeichen oder Gebetsgegenstände?', options: ['Kippa, Tallit und Tefillin', 'Mihrab, Minbar und Muezzin', 'Altar, Ambo und Tabernakel'], answer: 0, explanation: 'Kippa, Tallit und Tefillin gehören zum neuen Karteikartenblatt über jüdische Glaubenszeichen.' },
  { id: 'b24', topic: 'Gebäude & Schriften', prompt: 'Welche Zuordnung zu einem jüdischen Gegenstand ist richtig?', options: ['Mesusa–Türpfosten', 'Tefillin–Kirchturm', 'Tallit–Minarett'], answer: 0, explanation: 'Eine Mesusa wird am Türpfosten angebracht; sie enthält einen heiligen Text.' },
  { id: 'b25', topic: 'Gebäude & Schriften', prompt: 'Welcher Begriff bezeichnet religiöse Bilddarstellungen in einer orthodoxen Kirche?', options: ['Ikonen', 'Kalligrafie', 'Suren'], answer: 0, explanation: 'Ikonen stellen Christus, Maria, Heilige oder biblische Szenen dar.' },
  { id: 'b26', topic: 'Gebäude & Schriften', prompt: 'Welcher Ort ist kein Gebetshaus, sondern eine heilige Mauer?', options: ['Die Westmauer in Jerusalem', 'Die Synagoge', 'Die Moschee'], answer: 0, explanation: 'Die Westmauer ist ein wichtiger jüdischer Gebetsort, aber kein Gebetshaus.' },
  { id: 'b27', topic: 'Gebäude & Schriften', prompt: 'Was ist der Unterschied zwischen Muezzin und Imam?', options: ['Der Muezzin ruft zum Gebet; der Imam leitet das Gebet.', 'Der Imam ruft vom Minarett; der Muezzin ist Papst.', 'Beide Begriffe bezeichnen einen Toraschrein.'], answer: 0, explanation: 'Die Aufgaben in einer Moschee können sich unterscheiden: Gebetsruf und Gebetsleitung sind nicht dasselbe.' },
  { id: 'b28', topic: 'Gebäude & Schriften', prompt: 'Welche Dreiergruppe gehört zur orthodoxen Kirche?', options: ['Ikonen – Patriarch – orthodoxes Kreuz', 'Mihrab – Muezzin – Koran', 'Bima – Mesusa – Tora'], answer: 0, explanation: 'Ikonen und Patriarchen sind typische Begriffe orthodoxer Traditionen; Kreuzformen können sich unterscheiden.' },
  { id: 'b29', topic: 'Gebäude & Schriften', prompt: 'Welcher Gegenstand enthält kleine Abschnitte aus der Tora und wird beim Gebet getragen?', options: ['Tefillin', 'Tabernakel', 'Gebetsteppich'], answer: 0, explanation: 'Die Kapseln der Tefillin enthalten ausgewählte Torastellen.' },
  { id: 'b30', topic: 'Gebäude & Schriften', prompt: 'Welche Aussage über heilige Schriften ist richtig?', options: ['Der Tanach ist die jüdische Bibel; die Tora ist sein zentraler erster Teil.', 'Tanach und Tora sind Namen für den Koran.', 'Die Tora ist ein Teil des Neuen Testaments.'], answer: 0, explanation: 'Der Tanach umfasst Tora, Propheten und Schriften; die Tora besteht aus den fünf Büchern Mose.' },

  { id: 'c31', topic: 'Christentum', prompt: 'Aus welchen zwei Hauptteilen besteht die christliche Bibel?', options: ['Erstes/Altes und Neues Testament', 'Tora und Koran', 'Suren und Evangelien'], answer: 0, explanation: 'Die christliche Bibel besteht aus dem Ersten beziehungsweise Alten Testament und dem Neuen Testament.' },
  { id: 'c32', topic: 'Christentum', prompt: 'Wie ist die Angabe „66 Bücher“ zur Bibel genau einzuordnen?', options: ['Sie entspricht der evangelischen Zählung; andere christliche Traditionen zählen anders.', 'Alle christlichen Bibeln haben zwingend genau 66 Bücher.', 'Sie bezeichnet nur die Evangelien.'], answer: 0, explanation: 'Die evangelische Bibel zählt gewöhnlich 66 Bücher. Katholische und orthodoxe Bibeln enthalten weitere Schriften.' },
  { id: 'c33', topic: 'Christentum', prompt: 'Wie heissen die vier Evangelien des Neuen Testaments?', options: ['Matthäus, Markus, Lukas und Johannes', 'Abraham, Mose, David und Salomo', 'Petrus, Paulus, Jakobus und Judas'], answer: 0, explanation: 'Die vier Evangelien tragen die Namen Matthäus, Markus, Lukas und Johannes.' },
  { id: 'c34', topic: 'Christentum', prompt: 'Was bedeutet das griechische Wort „Evangelium“?', options: ['Frohe oder gute Botschaft', 'Heiliges Gesetz', 'Gebetsrichtung'], answer: 0, explanation: 'Evangelium bedeutet gute oder frohe Botschaft.' },
  { id: 'c35', topic: 'Christentum', prompt: 'Wie viele Sakramente kennt die römisch-katholische Kirche?', options: ['Sieben', 'Zwei', 'Fünf'], answer: 0, explanation: 'Es sind Taufe, Firmung, Eucharistie, Busse/Versöhnung, Krankensalbung, Weihe und Ehe.' },
  { id: 'c36', topic: 'Christentum', prompt: 'Welche zwei Sakramente erkennen evangelische Kirchen gewöhnlich an?', options: ['Taufe und Abendmahl', 'Firmung und Priesterweihe', 'Ehe und Krankensalbung'], answer: 0, explanation: 'In evangelischen Kirchen gelten Taufe und Abendmahl als Sakramente; Konfirmation und Trauung sind wichtige kirchliche Feiern.' },
  { id: 'c37', topic: 'Christentum', prompt: 'Was drückt die Taufe im Christentum unter anderem aus?', options: ['Aufnahme in die christliche Gemeinschaft und neues Leben im Glauben', 'Beginn des Ramadan', 'Übergabe einer Torarolle'], answer: 0, explanation: 'Die Taufe verbindet Wasser, Aufnahme in die Gemeinschaft und den Beginn eines Lebens im christlichen Glauben.' },
  { id: 'c38', topic: 'Christentum', prompt: 'Wie unterscheiden sich Firmung und Konfirmation?', options: ['Firmung–katholisches Sakrament; Konfirmation–evangelische Bekräftigung', 'Firmung–jüdisches Neujahr; Konfirmation–muslimisches Gebet', 'Firmung und Konfirmation–Namen für die Taufe'], answer: 0, explanation: 'Die Firmung gehört zu den katholischen Sakramenten. Die Konfirmation ist eine wichtige evangelische Feier, aber kein evangelisches Sakrament.' },
  { id: 'c39', topic: 'Christentum', prompt: 'Woran erinnern Brot und Wein bei Eucharistie oder Abendmahl?', options: ['An das letzte Mahl Jesu mit seinen Jüngern', 'An die Hidschra', 'An den Bund am Sinai'], answer: 0, explanation: 'Eucharistie beziehungsweise Abendmahl erinnern an Jesu letztes Mahl; die Konfessionen deuten die Feier unterschiedlich.' },
  { id: 'c40', topic: 'Christentum', prompt: 'Welche Reihe enthält nur katholische Sakramente?', options: ['Ehe, Busse, Krankensalbung und Weihe', 'Schabbat, Hadsch, Taufe und Ramadan', 'Konfirmation, Bar Mizwa, Zakat und Puja'], answer: 0, explanation: 'Ehe, Busse beziehungsweise Versöhnung, Krankensalbung und Weihe gehören zu den sieben katholischen Sakramenten.' },

  { id: 'i31', topic: 'Islam', prompt: 'In wie viele Suren ist der Koran gegliedert?', options: ['114', '66', '5'], answer: 0, explanation: 'Der Koran besteht aus 114 Suren.' },
  { id: 'i32', topic: 'Islam', prompt: 'In welcher Sprache wurde der Koran überliefert?', options: ['Arabisch', 'Hebräisch', 'Latein'], answer: 0, explanation: 'Der arabische Wortlaut hat im Islam eine besondere Bedeutung.' },
  { id: 'i33', topic: 'Islam', prompt: 'Wie werden Koranübersetzungen sachlich eingeordnet?', options: ['Sie helfen beim Verstehen; viele Muslime unterscheiden sie vom arabischen Original.', 'Übersetzungen sind im Islam grundsätzlich unbekannt.', 'Nur eine deutsche Übersetzung darf gelesen werden.'], answer: 0, explanation: 'Es gibt zahlreiche Übersetzungen. Viele muslimische Traditionen betrachten sie als Wiedergaben der Bedeutung, nicht als Ersatz für den arabischen Koran.' },
  { id: 'i34', topic: 'Islam', prompt: 'Wie entstand der Koran nach islamischer Überlieferung und historischer Einordnung?', options: ['Mohammed trug Offenbarungen vor; sie wurden mündlich und schriftlich bewahrt und nach seinem Tod gesammelt.', 'Mohammed schrieb ihn allein als fertiges Buch in einer Nacht.', 'Er wurde zuerst auf Latein verfasst.'], answer: 0, explanation: 'Die reine Aussage „anfangs nur mündlich“ ist zu einfach: Teile wurden auch zu Mohammeds Lebzeiten schriftlich festgehalten; die Sammlung wurde später vereinheitlicht.' },
  { id: 'i35', topic: 'Islam', prompt: 'Wie sind die Suren im Koran ungefähr angeordnet?', options: ['Nach der Eröffnungssure stehen längere Suren meist vor kürzeren.', 'Streng alphabetisch', 'Genau nach dem Geburtstag der Propheten'], answer: 0, explanation: 'Die Reihenfolge ist nicht rein chronologisch. Nach der kurzen Eröffnungssure nimmt die Länge im Allgemeinen ab, mit Ausnahmen.' },
  { id: 'i36', topic: 'Islam', prompt: 'Welche Inhalte findet man im Koran?', options: ['Glaubensaussagen, Erzählungen, ethische Weisungen sowie Gebote und Verbote', 'Nur eine Biografie Mohammeds', 'Nur Baupläne für Moscheen'], answer: 0, explanation: 'Der Koran enthält unterschiedliche Textarten und religiöse Orientierung.' },
  { id: 'i37', topic: 'Islam', prompt: 'Welche beiden Dinge nennt das neue Arbeitsblatt als verboten?', options: ['Alkohol und Schweinefleisch', 'Brot und Wasser', 'Milch und Früchte'], answer: 0, explanation: 'Das Blatt nennt den Verzicht auf Alkohol und Schweinefleisch als Beispiele islamischer Regeln.' },
  { id: 'i38', topic: 'Islam', prompt: 'Woran orientieren sich Muslime neben dem Koran häufig?', options: ['An der Sunna, dem überlieferten Beispiel Mohammeds', 'An den vier Evangelien als islamischem Gesetz', 'Nur an Landkarten'], answer: 0, explanation: 'Überlieferungen über Mohammeds Worte und Handlungen werden Hadithe genannt; zusammen prägen sie die Sunna.' },
  { id: 'i39', topic: 'Islam', prompt: 'Welche Aussage zur Sprache islamischer Gebete ist präzise?', options: ['Die vorgeschriebenen Rezitationen im Ritualgebet sind arabisch; persönliche Bittgebete können auch andere Sprachen verwenden.', 'Jedes Gebet muss immer deutsch sein.', 'Muslime dürfen nie in ihrer Muttersprache beten.'], answer: 0, explanation: 'Das Arbeitsblatt verallgemeinert. Für das rituelle Pflichtgebet ist Arabisch zentral; persönliche Duʿā-Gebete können in anderen Sprachen gesprochen werden.' },
  { id: 'i40', topic: 'Islam', prompt: 'Wodurch unterscheidet sich der Aufbau des Korans von der christlichen Bibel?', options: ['Der Koran ist in Suren gegliedert; die Bibel ist eine Sammlung verschiedener Bücher.', 'Der Koran besteht aus zwei Testamenten.', 'Die Bibel besteht aus 114 Suren.'], answer: 0, explanation: 'Suren sind die Kapitel des Korans. Die Bibel umfasst je nach christlicher Tradition eine unterschiedliche Zahl einzelner Bücher.' },

  { id: 'j31', topic: 'Judentum', prompt: 'Welche ungefähre Zahl jüdischer Menschen nennt das Video-Arbeitsblatt für die Schweiz?', options: ['Rund 18 000', 'Rund 1,8 Millionen', 'Genau 180'], answer: 0, explanation: 'Das Arbeitsblatt nennt rund 18 000. Solche Zahlen hängen vom Jahr und davon ab, wie Zugehörigkeit gezählt wird.' },
  { id: 'j32', topic: 'Judentum', prompt: 'Warum wird Gott im Judentum gewöhnlich nicht bildlich dargestellt?', options: ['Aus Ehrfurcht und wegen des Bilderverbots', 'Weil es im Judentum keine Kunst gibt', 'Weil Gott als Stern gedacht wird'], answer: 0, explanation: 'Die knappe Antwort „aus Ehrfurcht“ geht in die richtige Richtung; wichtig ist auch das Verbot, sich ein Gottesbild zur Verehrung zu machen.' },
  { id: 'j33', topic: 'Judentum', prompt: 'In welche Richtung wird Hebräisch gelesen?', options: ['Von rechts nach links', 'Von links nach rechts', 'Nur von oben nach unten'], answer: 0, explanation: 'Hebräische Schrift wird von rechts nach links gelesen.' },
  { id: 'j34', topic: 'Judentum', prompt: 'Wie heisst das jüdische Neujahrsfest?', options: ['Rosch Haschana', 'Jom Kippur', 'Chanukka'], answer: 0, explanation: 'Rosch Haschana ist das jüdische Neujahrsfest.' },
  { id: 'j35', topic: 'Judentum', prompt: 'Worum geht es an Jom Kippur besonders?', options: ['Um Umkehr, Vergebung und Versöhnung', 'Um die Geburt Jesu', 'Um die Pilgerfahrt nach Mekka'], answer: 0, explanation: 'Jom Kippur ist der Versöhnungstag. Menschen bitten Gott und Mitmenschen um Vergebung; Unrecht gegenüber anderen soll auch mit ihnen geklärt werden.' },
  { id: 'j36', topic: 'Judentum', prompt: 'Aus welchen drei Teilen setzt sich das Wort Tanach zusammen?', options: ['Tora, Neviim und Ketuvim', 'Taufe, Abendmahl und Gebet', 'Tora, Koran und Bibel'], answer: 0, explanation: 'Tanach ist ein Akronym aus Tora, Neviim (Propheten) und Ketuvim (Schriften).' },
  { id: 'j37', topic: 'Judentum', prompt: 'Wie entsteht eine Torarolle traditionell?', options: ['Ein ausgebildeter Schreiber schreibt sie von Hand auf Pergament.', 'Sie wird auf Stein gedruckt.', 'Sie wird als Tonaufnahme hergestellt.'], answer: 0, explanation: 'Eine Torarolle wird von einem Sofer sorgfältig auf Pergament geschrieben; der genaue Zeitaufwand ist nicht bei jeder Rolle gleich.' },
  { id: 'j38', topic: 'Judentum', prompt: 'Wohin ist der Toraschrein einer Synagoge ausgerichtet?', options: ['In Richtung Jerusalem', 'In Richtung Mekka', 'Immer nach Norden'], answer: 0, explanation: 'Der Toraschrein befindet sich gewöhnlich an der nach Jerusalem ausgerichteten Seite des Gebetsraums.' },
  { id: 'j39', topic: 'Judentum', prompt: 'Was ist das Ewige Licht in der Synagoge?', options: ['Ein Licht nahe dem Toraschrein', 'Der Chanukka-Leuchter mit neun Lichtern', 'Eine Kerze nur für Hochzeiten'], answer: 0, explanation: 'Das Ner Tamid oder Ewige Licht brennt beziehungsweise leuchtet nahe dem Toraschrein.' },
  { id: 'j40', topic: 'Judentum', prompt: 'Welche Zuordnung zum Synagogengottesdienst stimmt?', options: ['Kantor–Gesang; Siddur–Gebetbuch', 'Kantor–Toraschrein; Siddur–Leuchter', 'Kantor–Papst; Siddur–Koran'], answer: 0, explanation: 'Ein Kantor leitet den liturgischen Gesang; der Siddur ist ein jüdisches Gebetbuch.' },

  { id: 'b31', topic: 'Gebäude & Schriften', prompt: 'Was bedeutet das Wort „Synagoge“ sinngemäss?', options: ['Zusammenkunft oder Versammlung', 'Opfertisch', 'Gebetsruf'], answer: 0, explanation: 'Synagoge kommt aus dem Griechischen und bedeutet Zusammenführung oder Versammlung.' },
  { id: 'b32', topic: 'Gebäude & Schriften', prompt: 'Was enthält die Mesusa am Türpfosten?', options: ['Pergament mit Abschnitten des Gebets „Höre Israel“', 'Eine kleine Torarolle mit allen fünf Büchern', 'Weihwasser'], answer: 0, explanation: 'Die Mesusa enthält Pergament mit Toraversen, darunter dem Schma Jisrael.' },
  { id: 'b33', topic: 'Gebäude & Schriften', prompt: 'Wozu dient die Bima in einer Synagoge?', options: ['Als Ort oder Pult für die Toralesung', 'Als Behälter für Kippot', 'Als Taufbecken'], answer: 0, explanation: 'Auf der Bima wird die Torarolle aufgelegt und aus ihr vorgelesen.' },
  { id: 'b34', topic: 'Gebäude & Schriften', prompt: 'Welche Schmuckstücke können an einer Torarolle zu sehen sein?', options: ['Krone und Schild', 'Kreuz und Rosenkranz', 'Halbmond und Gebetsteppich'], answer: 0, explanation: 'Torarollen können unter anderem mit einer Krone und einem Schild geschmückt sein.' },
  { id: 'b35', topic: 'Gebäude & Schriften', prompt: 'Wie viele Lichter hat ein Chanukka-Leuchter vollständig?', options: ['Neun: acht Festlichter und ein Dienerlicht', 'Genau acht ohne weiteres Licht', 'Sieben wie die Tempelmenora'], answer: 0, explanation: 'Die Chanukkia hat acht Lichter für die acht Festtage plus das Dienerlicht Schamasch. Die Formulierung „achtarmig“ im Blatt ist ungenau.' },
  { id: 'b36', topic: 'Gebäude & Schriften', prompt: 'Welche Aussage zu Sitzordnungen in Synagogen ist richtig?', options: ['Geschlechtertrennung gibt es in orthodoxen Gemeinden; andere jüdische Gemeinden sitzen gemeinsam.', 'In jeder Synagoge sitzen Frauen zwingend auf einer Empore.', 'In keiner Synagoge gibt es unterschiedliche Sitzbereiche.'], answer: 0, explanation: 'Die Zeichnung zeigt eine traditionelle orthodoxe Anordnung, aber sie gilt nicht für alle Synagogen.' },
  { id: 'b37', topic: 'Gebäude & Schriften', prompt: 'Was unterscheidet Ambo und Altar in einer Kirche?', options: ['Am Ambo wird gelesen; am Altar wird Eucharistie oder Abendmahl gefeiert.', 'Der Ambo ist ein Kirchturm; der Altar eine Glocke.', 'Beide sind Namen für das Taufbecken.'], answer: 0, explanation: 'Der Ambo ist das Lesepult. Der Altar ist der Tisch der Eucharistie- beziehungsweise Abendmahlsfeier.' },
  { id: 'b38', topic: 'Gebäude & Schriften', prompt: 'Welche Gegenstände passen zur Taufe?', options: ['Taufbecken und Wasser', 'Bima und Torarolle', 'Mihrab und Gebetsteppich'], answer: 0, explanation: 'Bei der Taufe wird Wasser verwendet; sie kann durch Begiessen oder Untertauchen vollzogen werden.' },
  { id: 'b39', topic: 'Gebäude & Schriften', prompt: 'Welche Aussage zum Kippa-Behälter in der Synagogenzeichnung ist genau?', options: ['Manche Synagogen stellen Kippot für Besucher bereit; das ist kein zwingender Bauteil jeder Synagoge.', 'Jede Synagoge muss denselben Behälter besitzen.', 'Darin werden geweihte Hostien aufbewahrt.'], answer: 0, explanation: 'Ein Kippa-Behälter kann praktisch sein, gehört aber nicht zu den allgemein notwendigen Bestandteilen einer Synagoge.' },
  { id: 'b40', topic: 'Gebäude & Schriften', prompt: 'Welche Vierergruppe gehört vollständig zur Synagoge?', options: ['Toraschrein, Bima, Ewiges Licht, Siddur', 'Altar, Ambo, Tabernakel, Minbar', 'Mihrab, Qibla, Orgel, Taufbecken'], answer: 0, explanation: 'Toraschrein, Bima, Ewiges Licht und Siddur sind Begriffe aus dem Synagogen- und Gebetskontext.' },
];

export function shuffleIndices(length: number, random: () => number = Math.random): number[] {
  const result = Array.from({ length }, (_, index) => index);
  for (let index = result.length - 1; index > 0; index -= 1) {
    const target = Math.floor(random() * (index + 1));
    [result[index], result[target]] = [result[target], result[index]];
  }
  return result;
}

function practiceWeight(stat?: ItemStat): number {
  if (!stat?.attempts) return 4;
  const accuracy = stat.correct / stat.attempts;
  const needsReview = accuracy < 0.8 ? 2 : 0;
  return 1 + (1 - accuracy) * 7 + needsReview + Math.max(0, 2 - stat.attempts);
}

export function buildAdaptiveRound(
  filter: Topic | 'Alle',
  items: Record<string, ItemStat>,
  options: { onlyIds?: string[]; size?: number; random?: () => number } = {},
): string[] {
  const random = options.random ?? Math.random;
  const allowedIds = options.onlyIds ? new Set(options.onlyIds) : null;
  const pool = questions.filter((question) =>
    (filter === 'Alle' || question.topic === filter) && (!allowedIds || allowedIds.has(question.id))
  );
  const size = Math.min(options.size ?? (filter === 'Alle' ? 15 : 12), pool.length);
  return pool
    .map((question) => ({
      id: question.id,
      rank: -Math.log(Math.max(random(), Number.EPSILON)) / practiceWeight(items[question.id]),
    }))
    .sort((left, right) => left.rank - right.rank)
    .slice(0, size)
    .map(({ id }) => id);
}
