-- Shared family-learning schema. It supports this NMG app and future subjects/apps.
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.families (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now()
);

create table if not exists public.family_members (
  family_id uuid not null references public.families(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('parent')),
  created_at timestamptz not null default now(),
  primary key (family_id, user_id)
);

create table if not exists public.learners (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references public.families(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 40),
  created_at timestamptz not null default now()
);

-- Every future learning application registers one reusable catalogue row.
create table if not exists public.learning_apps (
  app_key text primary key check (app_key ~ '^[a-z0-9][a-z0-9-]{2,79}$'),
  title text not null check (char_length(title) between 1 and 120),
  subject text not null check (char_length(subject) between 1 and 60),
  grade_label text check (char_length(grade_label) <= 60),
  topic_labels jsonb not null default '[]'::jsonb check (jsonb_typeof(topic_labels) = 'array'),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.learning_apps (app_key, title, subject, grade_label, topic_labels)
values (
  'nmg-religionen-pruefung-1',
  'Weltreligionen · Prüfung 1',
  'NMG',
  '6. Klasse',
  '["Grundwissen", "Christentum", "Islam", "Judentum", "Gebäude & Schriften"]'::jsonb
)
on conflict (app_key) do update set title = excluded.title, subject = excluded.subject,
  grade_label = excluded.grade_label, topic_labels = excluded.topic_labels, active = true;

-- Each browser/app installation is an anonymous Supabase user linked to David.
create table if not exists public.learner_devices (
  learner_id uuid not null references public.learners(id) on delete cascade,
  device_user_id uuid not null references auth.users(id) on delete cascade,
  linked_at timestamptz not null default now(),
  primary key (learner_id, device_user_id),
  unique (device_user_id)
);

create table if not exists public.pairing_codes (
  id uuid primary key default gen_random_uuid(),
  learner_id uuid not null references public.learners(id) on delete cascade,
  code_hash text not null unique,
  expires_at timestamptz not null,
  claimed_at timestamptz,
  created_at timestamptz not null default now()
);

-- One baseline per app/device imports progress collected before cloud pairing.
create table if not exists public.legacy_progress (
  learner_id uuid not null references public.learners(id) on delete cascade,
  device_user_id uuid not null references auth.users(id) on delete cascade,
  app_key text not null references public.learning_apps(app_key),
  snapshot jsonb not null check (jsonb_typeof(snapshot) = 'object'),
  imported_at timestamptz not null default now(),
  primary key (learner_id, device_user_id, app_key)
);

-- Generic event model: score supports binary or partial credit in future apps.
create table if not exists public.learning_events (
  id bigint generated by default as identity primary key,
  client_event_id uuid not null unique,
  learner_id uuid not null references public.learners(id) on delete cascade,
  device_user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  app_key text not null references public.learning_apps(app_key),
  item_key text not null check (char_length(item_key) between 1 and 80),
  topic text not null check (char_length(topic) between 1 and 100),
  score numeric(5,4) not null check (score between 0 and 1),
  reward_points smallint not null default 0 check (reward_points between 0 and 100),
  duration_seconds integer check (duration_seconds between 0 and 86400),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  occurred_at timestamptz not null,
  received_at timestamptz not null default now()
);

create index if not exists learning_events_learner_app_time_idx on public.learning_events (learner_id, app_key, occurred_at desc);
create index if not exists learning_events_learner_topic_idx on public.learning_events (learner_id, app_key, topic);
create index if not exists pairing_codes_expiry_idx on public.pairing_codes (expires_at) where claimed_at is null;

alter table public.families enable row level security;
alter table public.family_members enable row level security;
alter table public.learners enable row level security;
alter table public.learning_apps enable row level security;
alter table public.learner_devices enable row level security;
alter table public.pairing_codes enable row level security;
alter table public.legacy_progress enable row level security;
alter table public.learning_events enable row level security;

create or replace function public.is_family_parent(p_family_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.family_members
    where family_id = p_family_id and user_id = auth.uid() and role = 'parent');
$$;

create or replace function public.is_learner_parent(p_learner_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.learners l
    join public.family_members fm on fm.family_id = l.family_id
    where l.id = p_learner_id and fm.user_id = auth.uid() and fm.role = 'parent');
$$;

create or replace function public.is_learner_device(p_learner_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.learner_devices
    where learner_id = p_learner_id and device_user_id = auth.uid());
$$;

create policy "parents read own families" on public.families for select to authenticated
using (public.is_family_parent(id));
create policy "parents read family membership" on public.family_members for select to authenticated
using (public.is_family_parent(family_id));
create policy "family reads learners" on public.learners for select to authenticated
using (public.is_family_parent(family_id) or public.is_learner_device(id));
create policy "authenticated users read app catalogue" on public.learning_apps for select to authenticated
using (active = true);
create policy "family reads linked devices" on public.learner_devices for select to authenticated
using (device_user_id = auth.uid() or public.is_learner_parent(learner_id));
create policy "parents read legacy progress" on public.legacy_progress for select to authenticated
using (public.is_learner_parent(learner_id));
create policy "parents delete legacy progress" on public.legacy_progress for delete to authenticated
using (public.is_learner_parent(learner_id));
create policy "family reads learning events" on public.learning_events for select to authenticated
using (public.is_learner_parent(learner_id) or device_user_id = auth.uid());
create policy "learner devices create learning events" on public.learning_events for insert to authenticated
with check (device_user_id = auth.uid() and public.is_learner_device(learner_id));
create policy "parents delete learning events" on public.learning_events for delete to authenticated
using (public.is_learner_parent(learner_id));

create or replace function public.ensure_parent_setup(p_display_name text default 'David')
returns table (learner_id uuid, display_name text)
language plpgsql security definer set search_path = '' as $$
declare
  v_family_id uuid;
  v_learner_id uuid;
  v_name text := left(coalesce(nullif(trim(p_display_name), ''), 'David'), 40);
  v_existing_name text;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) then raise exception 'parent account required'; end if;
  select l.id, l.display_name into v_learner_id, v_existing_name from public.learners l
  join public.family_members fm on fm.family_id = l.family_id
  where fm.user_id = auth.uid() and fm.role = 'parent' order by l.created_at limit 1;
  if v_learner_id is null then
    insert into public.families default values returning id into v_family_id;
    insert into public.family_members (family_id, user_id, role) values (v_family_id, auth.uid(), 'parent');
    insert into public.learners (family_id, display_name) values (v_family_id, v_name) returning id into v_learner_id;
  else
    v_name := v_existing_name;
  end if;
  return query select v_learner_id, v_name;
end;
$$;

create or replace function public.create_pairing_code(p_learner_id uuid)
returns text language plpgsql security definer set search_path = '' as $$
declare v_code text;
begin
  if not public.is_learner_parent(p_learner_id) then raise exception 'not allowed'; end if;
  delete from public.pairing_codes where learner_id = p_learner_id and (claimed_at is not null or expires_at < now());
  v_code := upper(substr(encode(extensions.gen_random_bytes(6), 'hex'), 1, 8));
  insert into public.pairing_codes (learner_id, code_hash, expires_at)
  values (p_learner_id, encode(extensions.digest(v_code, 'sha256'), 'hex'), now() + interval '20 minutes');
  return v_code;
end;
$$;

create or replace function public.claim_pairing_code(p_code text, p_app_key text, p_legacy_progress jsonb default null)
returns uuid language plpgsql security definer set search_path = '' as $$
declare v_code public.pairing_codes%rowtype;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if not exists (select 1 from public.learning_apps where app_key = p_app_key and active) then raise exception 'unknown learning app'; end if;
  select * into v_code from public.pairing_codes
  where code_hash = encode(extensions.digest(upper(trim(p_code)), 'sha256'), 'hex')
    and claimed_at is null and expires_at > now() for update;
  if v_code.id is null then raise exception 'invalid or expired pairing code'; end if;
  insert into public.learner_devices (learner_id, device_user_id)
  values (v_code.learner_id, auth.uid())
  on conflict (device_user_id) do update set learner_id = excluded.learner_id, linked_at = now();
  if p_legacy_progress is not null and coalesce((p_legacy_progress ->> 'totalAttempts')::int, 0) > 0 then
    insert into public.legacy_progress (learner_id, device_user_id, app_key, snapshot)
    values (v_code.learner_id, auth.uid(), p_app_key, p_legacy_progress)
    on conflict (learner_id, device_user_id, app_key) do nothing;
  end if;
  update public.pairing_codes set claimed_at = now() where id = v_code.id;
  return v_code.learner_id;
end;
$$;

revoke all on public.families, public.family_members, public.learners, public.learning_apps, public.learner_devices, public.pairing_codes, public.legacy_progress, public.learning_events from anon, authenticated;
grant select on public.families, public.family_members, public.learners, public.learning_apps, public.learner_devices, public.legacy_progress, public.learning_events to authenticated;
grant insert on public.learning_events to authenticated;
grant delete on public.legacy_progress, public.learning_events to authenticated;
grant usage, select on sequence public.learning_events_id_seq to authenticated;
revoke all on function public.is_family_parent(uuid), public.is_learner_parent(uuid), public.is_learner_device(uuid), public.ensure_parent_setup(text), public.create_pairing_code(uuid), public.claim_pairing_code(text, text, jsonb) from public;
grant execute on function public.is_family_parent(uuid), public.is_learner_parent(uuid), public.is_learner_device(uuid), public.ensure_parent_setup(text), public.create_pairing_code(uuid), public.claim_pairing_code(text, text, jsonb) to authenticated;
