-- Bidirectional, recoverable progress for every learner and learning app.

create table if not exists public.learner_settings (
  learner_id uuid primary key references public.learners(id) on delete cascade,
  reset_password text not null default upper(substr(encode(extensions.gen_random_bytes(4), 'hex'), 1, 6))
    check (char_length(reset_password) between 4 and 32),
  updated_at timestamptz not null default now()
);

-- A restored snapshot (or an intentional reset) becomes the new baseline.
-- Older immutable events stay available for backups/auditing but are no longer counted.
create table if not exists public.learner_app_controls (
  learner_id uuid not null references public.learners(id) on delete cascade,
  app_key text not null references public.learning_apps(app_key) on delete cascade,
  base_snapshot jsonb not null default '{"stars":0,"streak":0,"bestStreak":0,"totalAttempts":0,"topics":{}}'::jsonb
    check (jsonb_typeof(base_snapshot) = 'object'),
  cutoff_at timestamptz not null default '1970-01-01 00:00:00+00',
  updated_at timestamptz not null default now(),
  primary key (learner_id, app_key)
);

create table if not exists public.progress_backups (
  id bigint generated by default as identity primary key,
  learner_id uuid not null references public.learners(id) on delete cascade,
  app_key text not null references public.learning_apps(app_key) on delete cascade,
  snapshot jsonb not null check (jsonb_typeof(snapshot) = 'object'),
  snapshot_hash text not null,
  reason text not null default 'session' check (char_length(reason) between 1 and 40),
  source_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists progress_backups_learner_app_time_idx
  on public.progress_backups (learner_id, app_key, created_at desc);

alter table public.learner_settings enable row level security;
alter table public.learner_app_controls enable row level security;
alter table public.progress_backups enable row level security;

create policy "parents read learner settings" on public.learner_settings for select to authenticated
using (public.is_learner_parent(learner_id));
create policy "parents update learner settings" on public.learner_settings for update to authenticated
using (public.is_learner_parent(learner_id)) with check (public.is_learner_parent(learner_id));
create policy "parents read app controls" on public.learner_app_controls for select to authenticated
using (public.is_learner_parent(learner_id));
create policy "parents read progress backups" on public.progress_backups for select to authenticated
using (public.is_learner_parent(learner_id));
create policy "parents delete progress backups" on public.progress_backups for delete to authenticated
using (public.is_learner_parent(learner_id));

create or replace function public.empty_progress_snapshot()
returns jsonb language sql immutable set search_path = '' as $$
  select '{"stars":0,"streak":0,"bestStreak":0,"totalAttempts":0,"topics":{}}'::jsonb;
$$;

create or replace function public.merge_progress_snapshots(p_left jsonb, p_right jsonb)
returns jsonb language plpgsql immutable set search_path = '' as $$
declare
  v_left jsonb := coalesce(p_left, public.empty_progress_snapshot());
  v_right jsonb := coalesce(p_right, public.empty_progress_snapshot());
  v_topics jsonb := coalesce(v_left -> 'topics', '{}'::jsonb);
  v_topic text;
  v_stat jsonb;
  v_existing jsonb;
begin
  if jsonb_typeof(v_left) <> 'object' or jsonb_typeof(v_right) <> 'object' then
    raise exception 'invalid progress snapshot';
  end if;
  for v_topic, v_stat in select key, value from jsonb_each(coalesce(v_right -> 'topics', '{}'::jsonb)) loop
    v_existing := coalesce(v_topics -> v_topic, '{"attempts":0,"correct":0}'::jsonb);
    v_topics := jsonb_set(v_topics, array[v_topic], jsonb_build_object(
      'attempts', coalesce((v_existing ->> 'attempts')::int, 0) + coalesce((v_stat ->> 'attempts')::int, 0),
      'correct', coalesce((v_existing ->> 'correct')::int, 0) + coalesce((v_stat ->> 'correct')::int, 0)
    ), true);
  end loop;
  return jsonb_build_object(
    'stars', coalesce((v_left ->> 'stars')::int, 0) + coalesce((v_right ->> 'stars')::int, 0),
    'streak', greatest(coalesce((v_left ->> 'streak')::int, 0), coalesce((v_right ->> 'streak')::int, 0)),
    'bestStreak', greatest(coalesce((v_left ->> 'bestStreak')::int, 0), coalesce((v_right ->> 'bestStreak')::int, 0)),
    'totalAttempts', coalesce((v_left ->> 'totalAttempts')::int, 0) + coalesce((v_right ->> 'totalAttempts')::int, 0),
    'topics', v_topics
  );
end;
$$;

create or replace function public.get_consolidated_progress(p_learner_id uuid, p_app_key text)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare
  v_result jsonb := public.empty_progress_snapshot();
  v_cutoff timestamptz := '1970-01-01 00:00:00+00';
  v_snapshot jsonb;
  v_event record;
  v_topics jsonb;
  v_stat jsonb;
  v_streak int;
  v_best int;
begin
  if not (public.is_learner_parent(p_learner_id) or public.is_learner_device(p_learner_id)) then
    raise exception 'not allowed';
  end if;
  if not exists (select 1 from public.learning_apps where app_key = p_app_key and active) then
    raise exception 'unknown learning app';
  end if;

  select base_snapshot, cutoff_at into v_result, v_cutoff
  from public.learner_app_controls
  where learner_id = p_learner_id and app_key = p_app_key;
  v_result := coalesce(v_result, public.empty_progress_snapshot());
  v_cutoff := coalesce(v_cutoff, '1970-01-01 00:00:00+00');

  for v_snapshot in
    select snapshot from public.legacy_progress
    where learner_id = p_learner_id and app_key = p_app_key and imported_at > v_cutoff
    order by imported_at
  loop
    v_result := public.merge_progress_snapshots(v_result, v_snapshot);
  end loop;

  for v_event in
    select topic, score, reward_points from public.learning_events
    where learner_id = p_learner_id and app_key = p_app_key and received_at > v_cutoff
    order by occurred_at, id
  loop
    v_topics := coalesce(v_result -> 'topics', '{}'::jsonb);
    v_stat := coalesce(v_topics -> v_event.topic, '{"attempts":0,"correct":0}'::jsonb);
    v_topics := jsonb_set(v_topics, array[v_event.topic], jsonb_build_object(
      'attempts', coalesce((v_stat ->> 'attempts')::int, 0) + 1,
      'correct', coalesce((v_stat ->> 'correct')::int, 0) + case when v_event.score >= 1 then 1 else 0 end
    ), true);
    v_streak := case when v_event.score >= 1 then coalesce((v_result ->> 'streak')::int, 0) + 1 else 0 end;
    v_best := greatest(coalesce((v_result ->> 'bestStreak')::int, 0), v_streak);
    v_result := jsonb_build_object(
      'stars', coalesce((v_result ->> 'stars')::int, 0) + v_event.reward_points,
      'streak', v_streak,
      'bestStreak', v_best,
      'totalAttempts', coalesce((v_result ->> 'totalAttempts')::int, 0) + 1,
      'topics', v_topics
    );
  end loop;
  return v_result;
end;
$$;

create or replace function public.get_or_create_reset_password(p_learner_id uuid)
returns text language plpgsql security definer set search_path = '' as $$
declare v_password text;
begin
  if not public.is_learner_parent(p_learner_id) then raise exception 'not allowed'; end if;
  insert into public.learner_settings (learner_id) values (p_learner_id)
  on conflict (learner_id) do nothing;
  select reset_password into v_password from public.learner_settings where learner_id = p_learner_id;
  return v_password;
end;
$$;

create or replace function public.set_reset_password(p_learner_id uuid, p_password text)
returns void language plpgsql security definer set search_path = '' as $$
declare v_password text := trim(coalesce(p_password, ''));
begin
  if not public.is_learner_parent(p_learner_id) then raise exception 'not allowed'; end if;
  if char_length(v_password) < 4 or char_length(v_password) > 32 then
    raise exception 'password must contain 4 to 32 characters';
  end if;
  insert into public.learner_settings (learner_id, reset_password, updated_at)
  values (p_learner_id, v_password, now())
  on conflict (learner_id) do update set reset_password = excluded.reset_password, updated_at = now();
end;
$$;

create or replace function public.save_progress_backup(
  p_learner_id uuid,
  p_app_key text,
  p_snapshot jsonb default null,
  p_reason text default 'session'
)
returns bigint language plpgsql security definer set search_path = '' as $$
declare
  v_snapshot jsonb;
  v_hash text;
  v_last_id bigint;
  v_last_hash text;
  v_id bigint;
  v_reason text := left(coalesce(nullif(trim(p_reason), ''), 'session'), 40);
begin
  if not (public.is_learner_parent(p_learner_id) or public.is_learner_device(p_learner_id)) then
    raise exception 'not allowed';
  end if;
  v_snapshot := coalesce(p_snapshot, public.get_consolidated_progress(p_learner_id, p_app_key));
  if jsonb_typeof(v_snapshot) <> 'object' then raise exception 'invalid progress snapshot'; end if;
  v_hash := encode(extensions.digest(v_snapshot::text, 'sha256'), 'hex');
  select id, snapshot_hash into v_last_id, v_last_hash from public.progress_backups
  where learner_id = p_learner_id and app_key = p_app_key order by created_at desc limit 1;
  if v_last_hash = v_hash then return v_last_id; end if;
  insert into public.progress_backups (learner_id, app_key, snapshot, snapshot_hash, reason, source_user_id)
  values (p_learner_id, p_app_key, v_snapshot, v_hash, v_reason, auth.uid()) returning id into v_id;
  delete from public.progress_backups where id in (
    select id from public.progress_backups where learner_id = p_learner_id and app_key = p_app_key
    order by created_at desc offset 50
  );
  return v_id;
end;
$$;

create or replace function public.reset_progress_with_password(p_learner_id uuid, p_app_key text, p_password text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_expected text; v_snapshot jsonb;
begin
  if not public.is_learner_device(p_learner_id) then raise exception 'not allowed'; end if;
  select reset_password into v_expected from public.learner_settings where learner_id = p_learner_id;
  if v_expected is null or v_expected <> coalesce(p_password, '') then raise exception 'invalid reset password'; end if;
  v_snapshot := public.get_consolidated_progress(p_learner_id, p_app_key);
  perform public.save_progress_backup(p_learner_id, p_app_key, v_snapshot, 'before_reset');
  insert into public.learner_app_controls (learner_id, app_key, base_snapshot, cutoff_at, updated_at)
  values (p_learner_id, p_app_key, public.empty_progress_snapshot(), clock_timestamp(), now())
  on conflict (learner_id, app_key) do update set base_snapshot = excluded.base_snapshot, cutoff_at = excluded.cutoff_at, updated_at = now();
  return public.empty_progress_snapshot();
end;
$$;

create or replace function public.parent_reset_progress(p_learner_id uuid, p_app_key text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_snapshot jsonb;
begin
  if not public.is_learner_parent(p_learner_id) then raise exception 'not allowed'; end if;
  v_snapshot := public.get_consolidated_progress(p_learner_id, p_app_key);
  perform public.save_progress_backup(p_learner_id, p_app_key, v_snapshot, 'before_reset');
  insert into public.learner_app_controls (learner_id, app_key, base_snapshot, cutoff_at, updated_at)
  values (p_learner_id, p_app_key, public.empty_progress_snapshot(), clock_timestamp(), now())
  on conflict (learner_id, app_key) do update set base_snapshot = excluded.base_snapshot, cutoff_at = excluded.cutoff_at, updated_at = now();
  return public.empty_progress_snapshot();
end;
$$;

create or replace function public.restore_progress_backup(p_backup_id bigint)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_backup public.progress_backups%rowtype; v_current jsonb;
begin
  select * into v_backup from public.progress_backups where id = p_backup_id;
  if v_backup.id is null or not public.is_learner_parent(v_backup.learner_id) then raise exception 'not allowed'; end if;
  v_current := public.get_consolidated_progress(v_backup.learner_id, v_backup.app_key);
  perform public.save_progress_backup(v_backup.learner_id, v_backup.app_key, v_current, 'before_restore');
  insert into public.learner_app_controls (learner_id, app_key, base_snapshot, cutoff_at, updated_at)
  values (v_backup.learner_id, v_backup.app_key, v_backup.snapshot, clock_timestamp(), now())
  on conflict (learner_id, app_key) do update set base_snapshot = excluded.base_snapshot, cutoff_at = excluded.cutoff_at, updated_at = now();
  return v_backup.snapshot;
end;
$$;

revoke all on public.learner_settings, public.learner_app_controls, public.progress_backups from anon, authenticated;
grant select, update on public.learner_settings to authenticated;
grant select on public.learner_app_controls, public.progress_backups to authenticated;
grant delete on public.progress_backups to authenticated;
grant usage, select on sequence public.progress_backups_id_seq to authenticated;

revoke all on function public.empty_progress_snapshot(), public.merge_progress_snapshots(jsonb, jsonb),
  public.get_consolidated_progress(uuid, text), public.get_or_create_reset_password(uuid),
  public.set_reset_password(uuid, text), public.save_progress_backup(uuid, text, jsonb, text),
  public.reset_progress_with_password(uuid, text, text), public.parent_reset_progress(uuid, text),
  public.restore_progress_backup(bigint) from public;
grant execute on function public.get_consolidated_progress(uuid, text), public.get_or_create_reset_password(uuid),
  public.set_reset_password(uuid, text), public.save_progress_backup(uuid, text, jsonb, text),
  public.reset_progress_with_password(uuid, text, text), public.parent_reset_progress(uuid, text),
  public.restore_progress_backup(bigint) to authenticated;
